# CHAT-AR integration and retirement — working synthesis

> Context and re-entry memory, not owner approval or a complete history checkpoint.

## Current understanding

### Reviewed First Draft and Roadmap preparation — 2026-09-28

D-006 authorized the managed draft/review/preparation run. [FIRST-DRAFT](planning/chat-transport-simplification/FIRST-DRAFT.md), CHAT-SIMPLE-DRAFT-001 revision 1, contains exactly three candidate outcomes and four slice cards: C1-A server and C1-B client transport decomposition, C2-A unified chat command sending, and C3-A truthful status-send result handling. The proposed C1 → C2 → C3 sequence minimizes shared-file rework; C3 is independently fixable and this is not an owner-approved executable order. A fresh independent reviewer returned DRAFT_VALIDATED_FOR_DISCUSSION with no material findings (REF-013). The supervisor accepted the exact reviewed draft for discussion and Roadmap preparation.

The source check adds a crucial qualification to earlier boolean descriptions: the shared authenticated sender can return true for local pre-auth queue admission and false after a caught send exception. C2 must preserve the existing prompt distinction between enqueued, uncertain and not enqueued. C3 must handle a failed or uncertain status inquiry without asserting the original prompt was unsent, clearing its uncertainty gate or replaying it. Existing server acceptance, request/connection identity, provider retry ownership and the two-second live hourglass remain constraints.

Creator work R1–R4 covers exact queue/send outcome semantics, caller/response ownership and shared regression inventory, status-recovery transitions/correlation, and the exact dirty source/build baseline plus non-compounding review. No new owner product decision is required to begin that work. Bounded source analysis supports retaining later repair options under these constraints; broad accepted-response recovery, fresh-renderer hydration and failure-map UX remain D-005 work. Dependent plugin recovery consumers remain unreleased. The older broad recovery-first recommendation below is historical and superseded in scope by D-004/D-005. Proposed smokes are not passing tests. Temporary content-free diagnostics retain their future health-subscriber delete/migrate obligation.

### Deferred Fusion/OpenCode failure map and three-candidate First Draft — 2026-09-28

The owner recognized the earlier “Message accepted, but its response could not start” text as the actual warning they had seen and chose to leave the broad failure/status interaction issue for later (D-005). A separate parked [Map Fusion–OpenCode chat failure states](codex://threads/01a0ea32-f152-77a2-afc2-b73e8976685a) task in this same Chat Integration project carries the incident timeline, known code seams, OpenCode version/retry source, user-visible questions, and the instruction to wait until the three-candidate First Draft → Roadmap → Build → owner approval sequence finishes. The current folder retains D-004's three candidate boundaries; no draft, roadmap, SPEC approval or product build is claimed by this note.

For future analysis, distinguish Fusion's durable prompt acceptance, durable dispatch claim, per-turn OpenCode child launch, OpenCode's provider/API retries, native output, and Fusion's render/persistence/recovery. The installed `opencode --version` was 1.18.32; its official [retry policy source](https://github.com/anomalyco/opencode/blob/v1.18.32/packages/opencode/src/session/retry.ts) defines retryable failures and a five-retry ceiling, with exponential backoff and provider `Retry-After` support. This does not prove a retry was occurring in any observed failure. The adapter buffers canonical `turn_begin` before spawning but only yields it after spawn succeeds; a synchronous `spawn_throw` therefore fails before the turn begins, whereas normal provider retries inside the live child occur after begin. The current two-second `VisibleWaitActivity`/`WorkingActivity` hourglass already covers visible gaps during a live turn, including between chunks; it resumes/restarts with the reveal state and disappears on terminal. It is visual wait feedback, not proof of OpenCode liveness or a retry. A future explicit retry label would require a real signal; no duplicate wait timer is requested.

Current pre-begin `accepted_execution_failed` handling clears the sending target and places a notice above the composer, not in the assistant conversation position. Its current renderer-local feedback is separate from durable receipt readback. `prompt-submission-service.js` projects accepted/claimed as `unknown_after_dispatch_claim` even when a `provider_failed` reason was recorded; fresh-renderer accepted/no-exchange hydration remains unverified. A status query that loses a boolean false transport result can report “Checking delivery status” when no status frame left. D-004 keeps only that concrete false-send seam in the near-term third candidate. The later task must map all status/retry/terminal cases, preserve no automatic prompt resend, and propose the exact user-visible distinction for owner review. The already running temporary content-free logger retains its explicit delete/migrate marker for the future governed subscriber.

### Chat modularity against current standards — 2026-09-28 22:05 UTC

The owner asked whether the current chat implementation is simple and focused enough under the Code Standards and their Ousterhout-inspired design philosophy. Bounded current-byte review finds substantial positive decomposition: server authority owns accepted prompts and exact thread runtime, adapters contain native OpenCode translation, and many connected/presentation surfaces are focused. This is partial alignment, not a complete certification. The standards ask for one job per file, treat over 400 lines as a strong split signal, and prefer deep modules that hide complexity rather than more layers for their own sake.

The clearest excess is in transport entry points. Server `client-message-router.js` (918 lines) multiplexes unrelated domains but also validates/adopts prompts, coordinates view readiness and handles connection teardown inline. Client `ws-client.ts` (665 lines) owns authentication/reconnection and a broad set of domain response/store branches. Client `stream-handlers.ts` (509 lines) protects the live sequence frontier while also applying post-terminal metadata/autocomplete and accepted-prompt errors. Several connected chat hosts/actions send on `state.ws` directly, while the central `sendFusionMessage` has an authenticated, generation-aware boolean result; prompt recovery types that callback as `void`, losing a false-send signal. This is source-backed brittleness but not proof of the observed incidents' cause. The 407-line `ChatComposerModelMenu` is mostly a single menu job, yet it obtains an OpenCode-specific catalog inside presentation; consider its connected/presentation seam, not an automatic split. I-005 separately tracks reachable legacy history/open paths.

The recommended simplification order follows the failure boundary: verify/repair prompt-status and pre-begin accepted-message recovery, consolidate chat intent sends through an existing acknowledged transport owner, reduce inline server/client router policy into existing domain handlers, then retire confirmed legacy paths. Preserve one central ingress and the live frontier invariant; a broad file-splitting pass or new framework would add risk without a clearer contract. I-011 and REF-012 contain the precise source identity, standard references and limits. No product edit, test, restart, Git publication or acceptance change is claimed for this review.

### Broken status display and Diagnostics timer — 2026-09-28 08:28–08:42 UTC

The owner reported a “Checking delivery status” display, then a broken render where other threads could be clicked but would not open. A direct screen capture was unavailable and the owner could not identify the thread. Read-only `fusion.db` and temporary child-boundary logs had no new accepted receipt or spawn after the successful 08:26 UTC turn during the reported interval. The status could have been for that accepted attempt or a new request that never reached the receipt service; the request ID is unknown. Current `prompt-submission-recovery.ts` ignores the boolean false return of its transport function, a source-backed status-wait gap but not a proven cause. The owner saved the draft and authorized restart.

The owner also clarified that the “250 ms logger” may have meant the new Diagnostics display. The temporary server logger has no interval and uses the existing single log file descriptor. `ConnectedDiagnostics` samples at 200 ms while mounted and clears its interval on unmount. Each live server diagnostic subscription flushes at 100 ms, with dispose on unsubscribe/connection closure. The client text buffer is capped at 131,072 characters and the server subscription event queue at 131,072 UTF-16 units or 128 events; server subscriptions are limited to 16 per connection. These bounds make a simple accumulated diagnostic-text leak unlikely, but they do not establish that Diagnostics has no renderer cost. The Diagnostics channel remains open while its tab is open, even if its display is not the selected tab.

To distinguish a missing prompt/status/open frame from a renderer failure, the owner-authorized `temp_chat_boundary_v1` sink was extended with closed prompt, receipt-status and thread-open stages plus a 32-hex request ID and closed receipt outcome. No prompt text, thread title, argv, path, stderr or raw error is recorded. Two focused server suites passed 13/13 tests; changed source paths passed `git diff --check`. The owner-authorized canonical restart rebuilt the client and launched the dev app at 08:40 UTC on port 51857 (Electron PID 77002, server PID 77007, machine `RC-MacAir-15`); HTTP returned 200 and a post-restart thread-open request/return pair appeared in the temporary trace. The full-tree diff check still has an unrelated Office fixture EOF blank line.

Renderer PID 77021 measured 1,271,072 KB RSS just after restart, peaked at 2,666,688 KB within about two minutes, then fell to 1,498,400 KB by about four minutes; server PID 77007 fell from about 352 MB to near 110 MB. This shows large allocation and reclamation, not a proven accumulating leak. Diagnostics tabs are runtime-only and start empty after a restart; the 200 ms display timer requires a mounted tab, and no post-restart opening was observed by this agent. Memory is not yet attributed to Diagnostics, the Working timer or a specific tab. Targeted tab/subscription and memory correlation is needed before a fix. REF-011 preserves source hashes, scope and limitations; I-009 and I-010 track the separate status/navigation and memory questions. This observation does not resume the waived soak.

Accepted CHAT-AR implementation spans SPEC-01–06 and supplemental work, but the accepted bytes are not represented by HEAD alone. The original 45-minute soak, complete native/original-symptom checks, and 06C retirement/final integrated review were not completed as originally specified. A current-byte audit must decide what has already been retired and what plugin consumers actually depend on.

### Responsibility transfer — 2026-09-28 UTC

The owner selected this folder as the successor working-memory home (D-002). The source supervisor task is `01a0c1c8-6e85-7f83-8d67-2cb5c1476007`; setup/coordination task is `01a0e659-1933-7c30-b7ff-50476ea94d17`, inspected idle before this update. Neither identity is automatically registered as this folder's main history source. Actual tool CWD remains the fs-dev repository; this transfer does not relocate the app or create a new task.

Carry forward only the remaining close-out responsibilities:

1. Identify the exact integrated chat source/build baseline and reconcile accepted report manifests with subsequent local changes.
2. Inventory remaining retirement on production imports/listeners/stores, obsolete aggregate contracts, hidden legacy fallback, compatibility adapters and test-only bypasses. Do not assume all historical retirement targets are still present; SPEC-04/05 already retired substantial code.
3. Select affected public-route/build/lifecycle checks and reconcile the technical Chat wiki: responsibility maps, request/failure states, update-frequency boundaries, persistence/recovery, consumed contracts and known limits.
4. Prepare a bounded reviewed integration handoff for plugin consumers, with exact revision, actual checks, deviations, excluded changes and residual ownership. This is an intended deliverable, not a new approved execution plan.

The original quantified soak and complete native/IME/symptom checklist remain unperformed, not retrospectively passed. They do not automatically block the accepted closure or parallel planning. New repairs affecting input/render/resource behavior need proportionate affected checks. A known consumer-blocking defect is not optional simply because the original acceptance gate was superseded.

### Source and runtime continuity

Earlier read-only baseline observation: branch `agent/exact-workspace-paths`, HEAD `88637d11c65be53d4f2ad0f049f64a07fa3db1de`, with extensive uncommitted/concurrent work. HEAD alone does not contain the accepted implementation. Before parallel consumer builds, establish a reproducible owned snapshot/patch or separately authorized scoped commit; do not stage all, reset, publish or deploy by inference.

Owner subsequently requested the development app to preview SPEC-06 Diagnostics. The canonical restart workflow rebuilt successfully and launched from `/Users/rccurtrightjr./projects/fs-dev` with machine `RC-MacAir-15`; renderer caches/session storage were refreshed, not the chat database. Electron PID 62360 and server PID 62366 were both observed at 2026-09-28 06:26 UTC with an established connection on `http://localhost:50449`. This is the regular development preview, not the old isolated human-test fixture or Alpha. Leave it running; PID identities/port are dated observations and must be rechecked before any later operation.

### Bounded current-byte baseline check — 2026-09-28 06:57 UTC

Read-only comparison against RD-02's accepted `root-source.json` (SHA-256 `0a7dc263147fac3a29de1bd528cc940bf6cb44e720e147086a39b7e14d1c0ad7`) and `root-build.json` (SHA-256 `d66e0386a57a084f896d515a63a48f87e8318c0b983433fbb47f753024d40d4e`) at branch `agent/exact-workspace-paths`, HEAD `88637d11c65be53d4f2ad0f049f64a07fa3db1de`: 1,993/1,997 listed source paths matched byte-for-byte; all 200 listed build paths matched, with no extra files under `fusion-studio-client/dist`. Every present file under `fusion-studio-client/src`, `fusion-studio-server/lib`, and `fusion-studio-server/test` was covered by this source manifest, with no mismatches. Four listed paths differ: three `fusion-studio-client/e2e/chat-architecture/human-session{,-launch,-ownership}.mjs` fixture scripts and `System_Manager/ai-template/Issues/inbox/RCC-0096.md`. Two additional `human-session-resume` fixture files under the same e2e directory lie outside the manifest. REF-006 records exact evidence and limits.

This establishes a reproducible *listed-file* match to the latest accepted RD-02 source/build identity for the checked product paths, despite dirty Git status. It does not turn the later fixture changes into reviewed RD-02 bytes, certify runtime behavior, or prove coverage of resources/configuration outside the manifest. The 05:26 UTC preview build has matching dist bytes, but this check did not inspect the running renderer or execute a new test.

### Initial retirement inventory — 2026-09-28 06:57 UTC

Source inspection found the former `LegacyChatHost`, `useLegacyChatHost`, and `ViewWorksurfaceDock` files removed, while `WorkspacePanel`/`useViewChatHost`, `ChatSessionHost`/`useChatSessionHost`, and `ChatSurfaceComponentMount` supply the current view-bound and explicit-session surfaces. This is source placement evidence, not full retirement certification. The production open path still has a `resolveVisibleTarget` fallback in `thread-crud.js`/`thread-open-handler.js` when `threadGroups.resolveOpenTarget` is absent. The server still sends `history` from the Markdown chatlog mirror alongside canonical SQLite `exchanges`; the renderer uses the legacy `history` if `exchanges` is empty. `ThreadManager.getHistory` reads the mirror, while `getRichHistory` reads SQLite. A stale mirror could therefore supply display history in an empty-exchange response; whether this is reachable in a supported production state needs a bounded test/review before any removal. `HistoryFile.create` also retains a caller-compatibility no-op. These are candidate retirement surfaces, not proven defects or permission to delete compatibility behavior. The current Chat Wiki structure/UI pages describe the removed hosts as historical; a changelog line preserves its dated earlier claim.

### Candidate chat contracts for plugin/view consumers

The current Chat Wiki and matching source distinguish `threadGroupId` (visible Thread, membership and primary selection), `threadId` (exact transcript/runtime/prompt/Stop), `viewId` (view binding), durable `sideChatPlacementId` (tab placement), and transient `surfaceId` (one mount). `fusion.chat-surface` is currently a code-owned first-party registration; its strict descriptor carries `workspaceId`, `viewId`, `threadGroupId`, `threadId`, and `host`, and the mount validates the hydrated tuple before opening an exact member with `historyOnly: true`. This is an observed first-party bridge, not a general plugin grant or a contract for arbitrary packages. Passive `thread:open` hydrates, while assistant activation and `thread:action` mutations require the trusted shell role and server-side validation; SQLite exchanges and server-owned prompt receipts remain authoritative. Plugin-view provisioning should consume these narrow semantics through a separately governed capability rather than assuming direct socket, store, or database access. The exact plugin capability and first proving view remain with the sibling folders.

One already documented Side Chat presentation gap intersects that consumer boundary: `useChatSessionHost` forces `sidebarCollapsed` for `host === 'side-tab'`, `ChatAreaHeader` then renders the left “Show threads” control, and `useChatSessionActions` toggles the outer view sidebar from that Side Chat. The current Chat Wiki states the approved Side Chat target removes that left control. I-006 records this as a source-confirmed prerequisite to review before a plugin view freezes or copies the header behavior; no product fix is authorized by this note.

Preview guidance: open a chat → Chat options → Diagnostics → send a message. The build contains the native event-stream and counters surface. Computer Use failed with app-server error -10005, so the tab was not opened/visually verified by the supervisor. Startup logs included `runtime_descriptor_denied` and `native_ipc_denied` markers; no cause was established and no full UI-health assertion was made. No provider message or new soak was sent/run for preview. Logs: `/var/folders/ng/s9jvcvqs3sq9crldjc_5cvjh0000gn/T/fusion-electron.log` and sibling `electron-renderer.log`; launch refreshes these logs, so preserve relevant evidence before a later authorized restart.

### Related domains, not additional responsibilities

[Health/observability](../fusion-health-and-governed-observability/TICKET.md) retains dogfood/bookmark intake, reveal-backlog improvements, shared numeric measurements and the separate content-free logger. [Plugin foundation](../plugin-foundation/TICKET.md), [governed events/ledger](../governed-events-and-ledger/TICKET.md) and [plugin views/provisioning](../plugin-views-and-provisioning/TICKET.md) own their shared contracts. Escalate cross-boundary dependencies without creating duplicate implementation owners.

Latest owner direction favors plugin infrastructure first so new implementations can live as plugins from the outset. Exact `ai/plug-ins` versus `System/plugins/<plugin-id>` placement and first proving plugin remain for that domain to reconcile with the newer September 23 VISION. Do not execute a stale logger-before-packaging sequence. This folder consumes those decisions rather than choosing their contracts.

## Open discussion

Inventory the current integrated chat bytes and evidence, determine the exact baseline and consumed contracts, then shape bounded retirement and verification work. The owner will settle the full-versus-targeted verification scope in this folder. See [ISSUES](ISSUES.md) for decisions and source gaps that could change the result.

### Owner-requested independent investigations — 2026-09-28 UTC

At 07:37 UTC the owner asked for two adversarial checks of the current chat failure. CHAT-AR-INV-001 rev 1 (`/root/chat_adversarial_review`) owns only `investigations/CHAT-AR-INV-001/report.md`: compare current send/response/recovery behavior with the user-preference Wiki, routed Code Standards and Chat Wiki, then identify supported violations or consequential contract gaps. CHAT-AR-INV-002 rev 1 (`/root/chat_send_brittleness`) owns only `investigations/CHAT-AR-INV-002/report.md`: trace send, session binding, dispatch and persistence failure paths, including read-only database/resource metadata. Both were dispatched as bounded runtime children with read-only product scope; no tests that mutate runtime state, prompt sends, app restart, product edits, Wiki edits, publication or Alpha operation were assigned. The current task is the accountable recipient; no persistent main-history UUID or checkpoint cursor is inferred from their runtime child names.

Input identity at dispatch: `/Users/rccurtrightjr./projects/fs-dev`, branch `agent/exact-workspace-paths`, HEAD `88637d11c65be53d4f2ad0f049f64a07fa3db1de`, dirty; each investigator must fingerprint material dirty files. Shared starting Wiki SHA-256 values were `45fa9f630563d79935d5a461b308c823c0db3ded5c23817ba6d4c8a06c794ed5` (preferences), `de3995c68ae84f3b0fa389c6af0327e21dd08f30ac9ffbc7548b76f80ac393d7` (standards router), and `696afb2d3ec027256e783957c3461eb03300db0b97b34b3e62162977c22ed42f` (Chat overview). Relevant server source SHA-256 values: `runtime-prompt-admission.js` `efecc424f1b1dc52bb4b138769b2138b6b8a0de602b20186beb1f1067c279c17`, `runtime-dispatch.js` `c70060a511e611dd53516bee186f66ed30e84b59b25624893976b6806f3c2558`, `runtime-session-binding.js` `4ff35911f289ba84868f7ae6bce62ca9456442b1b98b32855082f23c2969c99b`, `prompt-submission-service.js` `c6c2ceb640e5aa9d8de221c9d8ca43899a263247da39b3d7a1ec380f72d36966`, and `db.js` `343780913d538c1dfddf0d430fb2c17ea7e1f3008e3d38936543fc9a29f6ca76`. These are dated file identities, not a clean checkout or integrated release.

Both reports were received at 07:40–07:42 UTC. REF-008 records their provenance and limitations. INV-001 is incorporated into I-008 for accepted-prompt recovery; its Side Chat and retirement findings corroborate I-006 and I-005. INV-002 is incorporated into I-007 for the dispatch failure and resource hypotheses. Their common finding is that the four prompts passed durable acceptance and dispatch claim, but a `wire_ready` session proxy does not prove the per-turn OpenCode child launched. No present log or receipt identifies the thrown error. The actual cause remains unresolved; a 15–19 ms receipt lifetime only suggests a fast failure. INV-001 also found that `provider_failed` receipts still read back as execution-unknown while the foreground error removes the client status control, and that a fresh renderer may omit an accepted prompt with no exchange/live turn. The latter is source-backed but needs an affected route check before it is called reproduced behavior. No report asserts that the provider received the prompts.

INV-002 measured a 167,026,688-byte development SQLite database dominated by historical event-ledger/file-change data; eight prompt receipts occupied about 8 KB including their index. It observed about 16,100 server file descriptors, mostly checkout files, after the incident. Actual process soft limit and incident-time FD count are unknown, so neither database size nor FD pressure is established as the cause. It also identified a conditional silent fallback to Kimi after a harness metadata DB lookup error; no evidence shows that branch ran during I-007. A subsequent Computer Use retry still failed with app-server error `-10005`, so the current desktop warning remains uninspected on screen.

At report return, the proposed minimum discriminating capture was content-free classification at the per-turn child boundary (actual harness, spawn attempted/PID/error code, exit state, native output/session-ID presence, and session-ID persistence), followed by a bounded accepted-pre-begin-failure/reopen check. The logging implementation is recorded below; the fresh-reopen check remains proposed. No SPEC-06 acceptance or waived-soak state changed.

### Temporary child-boundary diagnostics — owner authorization, 2026-09-28 UTC

The owner explicitly allowed temporary logging before the governed subscriber work, with a clear delete-or-migrate marker. A scoped product edit now adds `temp_chat_boundary_v1` records through the existing server log file from the OpenCode adapter and claimed-dispatch failure boundary. The closed projection contains stage, UUID thread/turn IDs, fixed harness IDs, PID, selected OS/SQLite/harness error codes, bounded exit code/signal and presence booleans. It excludes prompts, arguments, paths, stderr, provider JSON and raw error text. The temporary sink holds one log descriptor open from startup so a later `EMFILE` at child spawn can still be recorded; log I/O itself remains best-effort. `fusion-studio-server/lib/logging.js` carries `TEMP CHAT-AR I-007` with the explicit migration/removal target: the future governed content-free health subscriber. This private diagnostic is not a new governed event or a finished subscriber. REF-009 records changed-file identity and verification.

Five focused Jest suites passed (160 tests), covering log field closure, adapter spawn-error emission, OpenCode harness behavior, live diagnostic dispatch, prompt recovery and runtime controller behavior. The running development server PID 62366 and Electron PID 62360 still predate the edit, rechecked at about 07:49 UTC. The new records will appear only after a later development-app/server restart; no restart or fresh prompt was performed so the owner's current process state remains available. The temporary log does not retroactively reveal the exact 06:51–06:52 UTC exception. After a later restart and affected send, inspect only `temp_chat_boundary_v1` fields in `fusion-studio-server/server-live.log`, then remove or migrate the path when the subscriber contract is built. Do not leave it as a parallel permanent logger.

Later runtime update, 2026-09-28 08:06 UTC: the owner requested a development-app restart. The canonical `restart-fusion.sh --repo /Users/rccurtrightjr./projects/fs-dev --machine RC-MacAir-15` completed the client build and relaunched Electron PID 72921 with server PID 72934 at `http://localhost:51498`. The server returned HTTP 200, Electron logged navigation completion, and an established renderer/server TCP connection was observed. `lsof` showed the server holding `fusion-studio-server/server-live.log` open at FD 14, the new temporary sink's descriptor. These are startup/connection checks, not a test send or reproduction; no cause has yet been captured for I-007. The prior PID/port statements above remain dated observations.

### Recurrent child-launch failure — 2026-09-28 08:18 UTC

The owner reported the accepted-message warning again and said Electron required force reload both times it occurred; causality was left open. REF-010 binds the live read-only evidence. One OpenCode turn at 08:09 launched PID 73303 and closed normally with native JSON, session ID and turn end. A second turn on the same thread at 08:18 was accepted and dispatch-claimed, but `spawn_attempt` was followed immediately by synchronous `spawn_throw` and `dispatch_failure`, with no PID or bound turn. The receipt became `provider_failed` 24 ms after creation. The first diagnostic revision did not allowlist the thrown error's code, leaving its exact class unknown. The failed input was 206 bytes with no attachments or NUL, so its size alone does not explain an argument-limit failure. Server PID 72934 held about 16,145 descriptors, mostly regular checkout files; after restart, server PID 74930 again reached about 16,148 descriptors within minutes. Neither the actual FD soft limit nor a causal link to spawn was established. Electron logged a navigation interval at 08:12; the force-reload link is owner-reported, not proved by the log.

The temporary classifier was expanded with selected Node/OS codes, a closed error-name set, bounded errno and environment-ready status; 61 focused tests passed. A second canonical development restart at 08:24 UTC rebuilt and launched Electron PID 74921/server PID 74930 on `http://localhost:51629` with machine `RC-MacAir-15`. HTTP 200 and established renderer/server sockets were observed. No further prompt was sent for diagnosis; the next affected send can distinguish the synchronous failure. This addition is still temporary and must be migrated or deleted with the governed subscriber (health I-004/D-006).

At 08:26 UTC a later turn on the same thread launched OpenCode PID 75070 and closed successfully with native JSON, session ID and turn end. Its receipt remained accepted/claimed without `provider_failed`. The new classifier therefore still awaits a failed send, and the intermittent character of the observed launch failure remains.

### Live accepted-message failure — 2026-09-28 UTC

The owner waived the historical 45-minute soak for successor work (D-003) and reported seeing “Message accepted, but its response could not start. Review the conversation before sending a new message” in the running development app. At 07:18–07:26 UTC, Electron PID 62360 and server PID 62366 were still running on port 50449. Native Computer Use failed with app-server error `-10005`, so the app screen itself was not inspected. The live database at `fusion-studio-server/data/fusion.db` shows four 06:51–06:52 UTC receipts accepted, dispatch-claimed and `provider_failed` across two OpenCode threads; there are no new exchanges for those attempts. The OpenCode database/log has no corresponding new session/message records in that interval, while one isolated 07:24 UTC OpenCode probe with the configured Together model and Fusion's child-environment policy succeeded. The app process had approximately 16,100 open file descriptors during inspection; whether that contributed is unproven. The server's current log tee records generic diagnostic markers and does not append `console.error` details; Electron forwards only generic server stderr markers. No harness diagnostic row was persisted. Thus the precise exception is not yet recoverable from these logs. REF-007 has the bounded evidence and I-007 tracks diagnosis.

The warning is a user-facing recovery state, not proof the provider rejected a prompt. The receipt shows durable prompt acceptance followed by failure after dispatch claim. It is safer to inspect the affected conversation and receipt before retrying than to assume the prompt was never sent. No further prompt was sent through the affected app threads during this inspection.

## Routed outcomes

The owner approved this folder's distinct planning ownership in the current setup conversation; [DECISIONS](DECISIONS.md) records only that scope. Source records remain at their linked locations and no proposal or implementation has been approved by this synthesis.

D-002 now records the explicit responsibility transfer. Handoff completeness is distinct from source integration, implementation approval or verification completeness. The next useful step remains a bounded baseline/retirement inventory, not another global test marathon.
