---
name: Events And Ledger Decisions
description: Durable decisions for Fusion Studio events, Universal Event Bus usage, resource/render sync, ledger provenance, and future file versioning.
metadata:
  incoming-edges:
    - Events And Ledger
  outgoing-edges:
    - Events And Ledger Vision
    - Chat Harness And Event Flow
    - Universal Event Bus Standards
    - Resource Event Sync Controller
    - UI Action Provenance Module
    - Universal Ledger File Versioning and Provenance
  source-files:
    - fusion-studio-server/lib/event-bus.js
    - fusion-studio-server/lib/watch/core.js
    - fusion-studio-server/lib/watch/workspace-watcher.js
    - fusion-studio-server/lib/ledger/event-ledger-subscriber.js
    - fusion-studio-server/lib/chat-metadata/collectors/file-mutations.js
  connected-skills: []
  related-trigger-files: []
---

> **Schema correction authority (2026-07-15):** Apply the [provenance cross-article findings](../../../../Captures/008-Provenance-Temp/provenance-schema-findings.md) and owner direction in chat. Mechanical corrections apply now; decision-tagged branches remain unresolved until explicit owner approval.

Durable architectural decisions for events, resource sync, provenance, and the Universal Ledger.

## UEB Is The Canonical Firehose

The Universal Event Bus is the shared canonical provenance stream for system facts. Resource/render sync, ledger subscribers, metadata collectors, and future versioning consume accepted canonical events. TRIGGERS.md file-change execution retains its single operational workspace-watcher matcher so provenance failure cannot suppress automation; canonical resource/automation events independently record and correlate it.

Producers preserve facts. Subscribers filter.

`eventId` is unique canonical event/graph identity. `eventFamily` plus dotted `eventType`, such as `resource.changed` or `workspace.switched`, is canonical classification. Colon strings such as `resource:changed` are bus topics or transport names only.

Canonical candidates that feed subscribers pass registered validation before UEB fan-out when practical, or through a validated-or-diagnosed publisher. Invalid candidates are withheld from canonical-only subscribers and produce structured diagnostics. This validation applies to the record, not the source operation; provenance failure never rejects or rolls back an otherwise valid interaction or mutation.

After operational validation accepts a command, the operational command path starts before initiating provenance such as `ui.action` is submitted to the supervised admission executor. The command/response chain never calls or awaits construction, redaction, validation, admission, or an accepted-reference promise. Downstream producers bind a ref only when the command-scoped slot is already filled; otherwise they omit the relationship and diagnose without waiting. A `resource.*` fact exists only after the owning mutation succeeds; resource provenance/recovery work is scheduled after that success and outside its result/response chain. Optional enrichment is included only when already available. After admission and only under owner-approved `UEB-D01`, UEB offers each eligible listener as a separate bounded supervised-executor task in deterministic order. Admitted tasks re-enter captured async-chain context and observe returned-promise rejections; saturation independently skips/finalizes only the affected delivery, and one callback never prevents later callbacks from being offered under D01's fairness rules. Subscriber synchronous filesystem/database/provider I/O is forbidden.

Operational attachment validation and provenance subject normalization produce separate lists. Provenance consumes an immutable snapshot after the prompt's operational attachment decision and may not mutate, filter, reorder, default, expand, or reject that operational list. A provenance-invalid attachment can remain operationally valid and present in the prompt while being omitted only from canonical `resources[]`; an all-provenance-invalid list still sends the unchanged valid prompt.

Canonical publication accepts only a private `PreparedCanonicalCandidate`. `prepareCanonicalCandidate` strips caller proof fields, consumes upstream refs, inserts each fully proven registered atomic relationship group, and records private pointer/ref proof; copying the same string from `inspectAcceptedRef` is insufficient. Missing, mismatched, stale, forged, wrong-workspace, unbound, or raw proof omits the whole affected group with exact `accepted_relationship_unbound` while an otherwise valid relationship-free base fact remains eligible. Whole-candidate suppression is limited to invalid required fact core, an unsanitizable base after relationship removal, unrelated final schema error, or UEB failure. UEB admission clones/freezes the safe event, binds its registered identity to an opaque ref, and freezes one `{ acceptedRef }` context. Every admitted listener task uses exact ABI `listener(frozenEvent, deliveryContext)` with the same event/context/ref; bare-ref argument two is invalid and identity-sensitive consumers use `assertAcceptedDelivery`. A false publication result exposes no event/ref/context and queues nothing. Loop keys use the frozen identity's `eventId`; admitted tasks re-enter captured async context.

## Chokidar Is Observation, Not Causation

The filesystem watcher can report that a file changed, but it usually cannot prove who caused the change. Watcher-origin events must stay honest about that limitation.

Known UI, assistant, harness, trigger, scheduler, script, sync, import, agent, or system actions should carry their own causal IDs so later subscribers can connect a mutation to the action that caused it.

## Resource Sync Is System Behavior

React/resource sync is not TRIGGERS.md behavior. UI consistency must be handled by deterministic application code that consumes UEB events and updates central state/cache.

TRIGGERS.md keeps one operational workspace-watcher matcher for file changes, and mutation handlers do not invoke a second matcher. Canonical UEB events independently record and correlate the observation. Trigger execution neither controls renderer freshness nor depends on provenance admission. Missing/rejected provenance may omit an accepted relationship, but cannot suppress or duplicate an applicable trigger.

Operational file-change trigger predicates use the closed watcher key set and exhaustive byte/operand grammar defined by SPEC-32, including signed safe integers for negative `delta`, bounded no-escape strings, and null only for `ext|oldPath|newPath`. Unknown/canonical/provenance keys or any invalid combination reject only that file block before evaluation and never default true. Slice 32e side-effect-free parses/classifies mixed trigger files, validates file blocks, and atomically replaces watcher filters. Cron and bus blocks never use this grammar and retain their one-time registration lifecycle; workspace reload cannot duplicate/remove them. Workspace parse failure installs no old-root filters, while same-workspace fatal reload retains the last valid set. Optional provenance is correlation-only after execution.

The complete file-block schema is closed. Slice 32e alone owns watcher repoint/recompile; Slice 32d preserves the current matcher and cannot assume the new controller. Slice 32e loads immutable base filter descriptors once, but instantiates declarative actions and workspace-side-effecting programmatic factories per opaque watcher `{workspaceRoot,generation}`. The controller owns unforgeable generation capabilities. After RSC-D16 closes, synchronous entry to the Slice-32b0 coordinator's watcher hook verifies the next ordered transition pair, makes B/null current, irreversibly invalidates A, attaches B handlers, starts supervised/watchdog-bounded A-close/B-ready/reconciliation, and returns a non-Promise acknowledgment. Those tasks never hold the coordinator; A completion cannot regain currency, and current ready/reconciliation failure or expiry enters bounded `degraded_recovery_pending` plus exactly one direct freshness recovery. Every action checks currency before work, after every await/callback boundary, and immediately before each irreversible effect. Timers/queued callbacks retain the capability and stale ones no-op. Atomic replacement preserves descriptor identity while preventing startup-root closure reuse; B effects target only B. Concurrent requests become adjacent coordinator transitions, obsolete or never-settling work cannot affect/block the next generation, and reconciliation never synthesizes trigger execution. Workspace trigger reload cannot affect cron/bus listeners.

Slice 32b0 owns operational workspace serialization before Slice 32e. Every active switch/create/remove/ribbon ingress synchronously enqueues into one FIFO coordinator before lookup or reading active state. The coordinator transactionally commits active registry/last-active state, updates memory after commit, owns authoritative workspace/root resolution, and delivers the exact adjacent pair through a closed registry of audited bounded synchronous hooks; session fields are display caches only, and generic EventBus promises/controller/ribbon direct writes cannot define ordering. Synchronous I/O, unbounded CPU, and user/plugin callbacks are forbidden because no in-process contract can recover from a function that never returns. Broadcaster delivery is at-most-once with reconnect/snapshot recovery, and the watcher acknowledges synchronous invalidation/install while its detached async work is supervised. Hook throws, returned thenables, and detached background failure/nonsettlement cannot block the next intent, create a reversed/stale pair, or let provenance participate in the operational commit.

Open owner decision `RSC-D16` blocks Slice 32e. It must approve exact positive millisecond watchdogs for old-watcher close diagnostics, current-generation readiness, and reconciliation; monotonic clock/timer/config/test ownership; minus/exact/plus boundary behavior; cancellation on generation change/shutdown; and diagnostic/recovery dedupe. Ready/reconciliation expiry enters `degraded_recovery_pending` and issues exactly one current-generation freshness recovery; close expiry is cleanup diagnostic only. No default may be invented and no watchdog participates in provenance or blocks the workspace FIFO.

`ULV-D12` remains an owner-decision blocker before 40b2d1 or any non-batch canonical file-version emission/persistence. It must define the exact file-version event types; phase/lifecycle and common-envelope presence/status; ID/actor/provenance/context/resource/redaction/omission matrices; identity and idempotency; deterministic bounds; ordering/dedupe/replay/retry/restart; safe failure forms; and subscriber/ledger transaction boundaries. Conceptual optional, `unknown`, or generic-record sketches supply no defaults.

## Views Should Not Own Private File Watch Paths

Built-in views should read resources through central cache/state. View-local WebSocket listeners, private recursive file loading, and direct cache writes are migration targets because they can drift from ledger provenance and from each other.

Wiki, File Viewer, Capture, Office, Email, Agents, Tickets, and System views should eventually describe their resource needs through shared policy instead of each inventing refresh behavior.

## Render Freshness Comes From Targeted Cache Invalidation

The app should not manually patch DOM nodes to keep views fresh. Resource events should invalidate the smallest affected tree, content, style, config, or registry cache key, then React should reconcile from stable state.

Ordinary file changes should not clear a whole view, active document, selected tab, scroll position, or navigation history unless the active resource itself disappeared.

## Provenance Fields Have Separate Jobs

Event metadata must separate the path that produced the canonical event, the subsystem that observed the fact, the actor or context that initiated work, and the UI/view context present at command time.

`provenance.source` describes the canonical event producer. `provenance.observedBy` describes the subsystem that detected the fact. `provenance.origin` describes the initiating context when known. `actor` describes who or what is believed responsible. `context` carries view, panel, route, client, and active-resource details.

Root event, parent event, thread, turn, correlation, and causation IDs belong under `ids`. `provenance.cause` is reserved for schema-approved durable upstream initiator IDs such as UI action, tool call, harness ID/run/event, automation run, or audit query IDs. Trigger/scheduler/script/agent subtype causes remain `AUT-D03`/finding-1 candidates rather than settled common fields.

An operational runtime ID is not automatically a durable upstream cause. UI, automation, tool, and harness producers expose a propagatable reference only after the corresponding canonical event is accepted. Rejected or unpublished IDs never appear in downstream ID-bearing origin, cause fields, mirrors, or ledger edges.

Harness identity is provider-neutral. Use `harnessId`, `harnessRunId`, and `harnessEventId` for canonical harness attribution. Provider-native IDs such as OpenCode session IDs, message IDs, or event IDs are preserved under provider-keyed `nativeRefs` or provider-specific payloads, not as first-class Universal Ledger fields.

Resource mutation events must include workspace identity under `ids.workspaceId` and an observer under `provenance.observedBy`. Server-produced resource mutations must carry a generated or propagated `ids.serverMutationId`; watcher-observed resource facts prohibit it, and unrelated workspace/view lifecycle events omit it.

Workspace/path/operation are part of the safely resolved resource fact core. Other attribution, context, enrichment, hashes, counts, cause IDs, native refs, and persistence projections degrade to unknown, explicit omission/unavailable state, or diagnostics when absent. Ledger, versioning, redaction, compaction, and audit failures are isolated from source interactions. Redaction failure omits unsafe material and derived hashes/previews rather than failing the source operation.

## UI-Origin Mutations Capture Active Context

When a mutation starts from Fusion Studio UI, the renderer sends only non-ID active panel, active view, selected path, active tab/document, route, and similar UI context at command time. It does not supply canonical workspace, thread, turn, root, parent, correlation, causation, selected-resource, or other relationship IDs.

The renderer may create an optional `clientCommandId`; existing numeric view-state `clientMutationId` values remain acknowledgement/order tokens. The accepting server derives workspace identity/root/transition only from the coordinator-captured `WorkspaceCommandContextRef`; session workspace/root is cache-only. Renderer context/resources are admitted only after the recipient-specific private token binds to that ref and server path/target re-resolution succeeds. Initial workspace ID/root/panel roots arrive in one atomic server snapshot; it includes a token only if detached allocation already completed, otherwise a later exact-current metadata-only update may install one. Init/switch never calls or awaits entropy. The token binds the exact transition capability, so there is no separate client revision. Operational `set_panel` runs once after init restoration or explicit human change. Metadata recovery uses a distinct side-effect-free `request_panel_config`, is bounded/coalesced, and never re-enters panel/session/thread operations. A ready response requires the already-installed current token plus coordinator-derived workspace ID/root equality and may update only the named server-resolved panel root. Missing, stale, malicious, or outside-root metadata is ignored/refetched without affecting the valid panel or user operation.

The renderer token exists only in one module-private memory slot keyed by the exact current WebSocket object. It is excluded from Zustand, workspace/panel/view caches, state pushes, browser/Electron persistence, URL/history, and every serialized snapshot. Init/switch clears before optional install; a metadata-only update installs only on exact current socket/workspace/root equality; close, explicit disconnect, socket replacement, and shutdown clear synchronously before another prompt read or reconnect scheduling. Prompts read only for the current OPEN socket. After owner-approved `RSC-D17`, server allocation runs in that decision's bounded detached abort-aware executor with at most four async CSPRNG attempts; transition/disconnect takes its exact cancellation/finalizer branch and late completion is discarded. Before D17 closes, allocation/transport is not activated. Missing/invalid/paused/saturated entropy, capacity failure, or clear failure omits metadata, releases only bounded state, and never retries or affects the prompt or workspace operation.

No renderer `uiActionSeed` reaches the prompt wire before the server prompt log-removal fence and wire attachment ship atomically. Prompt-family server ingress and token-bearing renderer ingress call no console/debug/logger/redactor/formatter/stringifier or logging executor with raw, parsed, type, rejection, error, or seed material. After original handling, observability is only a module-private saturating counter selected from a closed compile-time type/outcome enum; it contains no values, has no callback, is fixed O(1), serializes/persists nothing, and cannot backpressure. Parse/route rejection increments only fixed counters. Static bidirectional inventory and zero-call sentinels fail on a new logger/serializer/error path or provenance wire field.

Renderer prompt-time provenance capture is limited to 32 subjects, 512 charged pure steps, and a 16,384-byte UTF-8 seed. Every root/path/intermediate has dual 4,096 code-unit/UTF-8-byte caps, identifiers dual 256 outer computational caps, and names/extensions dual 512 caps. Optional `clientCommandId` has the narrower exact `[A-Za-z0-9_-]{1,128}` semantic rule: wrong-format or 129-256 input is omitted without losing the envelope, while above-256 exhausts capture. O(1) code-unit then cap-plus-one byte checks and precomputed join lengths run before any string/path-library operation; no helper receives an over-cap operand. Capture performs no I/O, await/thenable, entropy, dynamic import, provider/filesystem access, user/plugin callback, or unbounded traversal. Exhaustion/error omits the whole seed with fixed `ui_provenance_capture_unavailable` while the already-fixed baseline prompt and complete operational attachment list send once unchanged.

After operational prompt validation starts the source command, the server treats `uiActionSeed` as untrusted and performs only the fixed-schema nonrecursive SPEC-34 extractor: maximum depth 4 from the seed, 207 charged own-data property reads including the message seed, array length, and 32 indexed element descriptors, 170 scalars, 32 subjects, an exactly enumerated 1,034-step ceiling, and 16,384 UTF-8 output bytes. Each private seed subject carries its required strictly increasing original operational attachment index. Target evidence is direct-read only at those positions from the already-required validated attachment vector and becomes at most 32 exact five-field null-prototype data copies with separate 129-property/160-scalar/exact 901-step/16,384-byte caps. Gaps are allowed; duplicates, reordering, holes, out-of-range/non-accepted entries, or type/path mismatch omit UI provenance. The indices/ordinals are stripped before canonical construction. No map/key scheme, scan, handle, attachment/vector entry, callback, capability, operation object, or graph reference enters the queue. Structural/budget/preflight/direct-read failure yields only fixed `ui_provenance_seed_unavailable`, submits no UI candidate, and leaves the prompt unchanged. The bounded seed/target copies enter D01 only with the bound context below; D01 accounts and releases all three on every terminal/cancellation/expiry/saturation/cleanup/shutdown branch.

The opaque command ref/token are also never queued. At command acceptance, bounded nullable owner-cell initialization either installs private `open_empty` state or disables only provenance; command `finally` atomically closes a non-null cell. After the operational path starts, the exact closed `bindUiProvenanceContextForQueue` performs only 24 charged sites: two registry lookups, five fixed shape checks, four capped workspace-ID/root scans, four connection/workspace/root/transition comparisons, three binding/liveness decisions, one allocation, three writes, one freeze, and one outcome. It emits null or frozen `{ schemaVersion: 1, workspaceId, workspaceRoot }`, capped at 4,608 UTF-8 bytes, with no connection/token/transition/ref/registry/external reference. Seed/target/binding failure reports only its fixed omission and allocates no slot/link. On full preflight success, the ref/token are discarded. Nullable slot failure installs/offers nothing; a non-null slot installs only into an open cell, while `owner_closed` terminalizes/releases it without offer. Successful install invokes the module-private fixed offer in the same non-yielding turn, and the offer receives that slot only as a synchronous nonqueued input. D01's UI-task data plane receives and accounts/releases exactly the bounded seed, target array, and bound context. Its sole queued control-plane value is one private D01-created/accounted `AcceptedRefSlotTaskLink`; only that link can settle the slot. Link creation/measurement/setup/rejection failure terminalizes the installed slot exactly once and releases all partial state. No other UI input, queued owner cell/slot handle, caller callback/finalizer, or command-context handle is retained.

Here, the bounded seed is not the token-bearing renderer/private seed type. The extractor returns a frozen transient wrapper containing the workspace token as a sibling of an already-frozen recursively readonly token-free `UiActionQueuedEnvelope`. Binder/target preflight consumes and drops the wrapper/token before slot allocation, passes the same envelope object without another copy, and D01's exact three queued data values are that envelope, target copies, and bound context. Static ABI and reachability tests make the token/wrapper absent and unreachable from queued, active, and cancelling task state.

Every renderer-workspace binding failure reports exactly frozen `{ code: 'workspace_context_unbound' }` to a dedicated sink that accepts only that one-key literal. The sink retains only one process-local saturating counter, may log only the fixed code, serializes/persists nothing, and resets on restart. It categorically forbids token, path/root, workspace, connection/client, transition/capability, panel/attachment, reason/subcode, message/stack, and exception-derived values. Its failure is swallowed and cannot affect the valid operation.

Upstream root/parent/causation event IDs come only from an `AcceptedCanonicalRef` or fully revalidated historical capability that embeds its validated workspace ID. Parent is the immediate producing predecessor; root is that predecessor's accepted root-or-self; causation is the registered direct initiating event. Workspace-scoped candidate/source IDs must match unless a future exact cross-workspace selector and operation-bound authorization capability are registered; the first package registers none. Correlation comes from an accepted reference or a fresh server-generated chain ID. Raw event/causation/workspace IDs in mutable state never qualify. Unknown legacy renderer relationship-ID fields are discarded. After binding, the server may generate durable `uiActionId` and use best-effort optional renderer details. Binding failure creates no candidate/ID/ref/edge, records only a value-free diagnostic, never uses the redaction-failed safe core, and never affects the valid source command. Resource mutations carry their root/parent/causation and `provenance.cause.uiActionId` from the same accepted upstream UI action when present; never create a dangling or cross-workspace cause.

For a canonical fact whose required operational core is already safe, accepted-relationship proof failure is field-local. Every absent, stale, forged, mismatched, wrong-workspace, wrong-selector, or unavailable live/historical proof atomically omits its registered relationship group and reports exact frozen `{ code: 'accepted_relationship_unbound' }`; the relationship-free fact remains eligible for admission. The dedicated sink retains only a process-local saturating count and no values. Whole-fact omission is reserved for invalid required fact core, unsanitizable safe base, unrelated final schema error, or publication failure. Renderer workspace binding is different because workspace/path are the required UI fact core: failure creates no `ui.action` but still never affects the prompt.

Connection/client/receiver identifiers are transient server-owned routing state, not authorization, stable identity, or causality. They are not first-slice canonical or ledger fields. Future multi-client work may approve optional server-stamped transport metadata without making interaction depend on it.

## Unknown External Changes Stay Unknown

If a mutation is not linked to UI, assistant, trigger, scheduler, script, sync, import, or known system work, the event should remain external or unknown instead of guessing.

This matters for later forensic queries. A false causal link is worse than an honest unknown.

## File Versioning Is A Ledger Subscriber

SQLite file versioning should consume canonical resource events rather than becoming a second watcher or mutation pipeline.

The resource-sync build only needs to preserve stable `eventId` values, workspace/resource identity, before/after-capable metadata, `ids`, `actor`, `provenance`, `context`, and `resources[]`. Snapshot storage, diff storage, retention, storm compaction, and assistant history queries belong to the versioning build unless explicitly folded into the current work.

## Ledger Traversal Requires Edges And Indexes

Durable file versions should not be isolated rows. Canonical events should be stored with their original event family/type and linked through graph edges so audits can traverse from UI actions, chat turns, tool calls, automation runs, resource mutations, file versions, restores, and audit queries.

Ledger storage should include validation status, edge/resource projections, and indexes for workspace, resource/path, event family/type, thread, turn, tool call, UI action, harness ID, harness run, harness event, automation run, audit query, correlation ID, causation ID, root/parent event ID, edge endpoints, and timestamp range. Trigger/script/scheduler/agent subtype indexes exist only if `AUT-D03` approves the corresponding fields and selectors. Provider-native IDs can be indexed inside provider-keyed `nativeRefs` or provider-specific payloads when a harness adapter needs replay or dedupe queries. Payload hashing and redaction rules are required before broad snapshot, diff, or tool-output persistence.

Ledger payload storage is never a blind original-payload copy. Complete JSON and compact projections come only from the validated safe form. A failed-redaction safe core is canonical only when its domain registry defines and admits that exact branch; in the first package this is UI only. Resource/lifecycle redaction failure produces no canonical event/reference and invokes non-canonical freshness recovery. If an inconsistent accepted event reaches ledger, ledger still stores only the restricted ledger-only defensive fallback and diagnostic. That fallback is not a canonical safe core, cannot provide historical relationship proof, and does not retroactively make the event valid. No material-safety branch changes the source operation.

Open owner decision `LED-D01` blocks SPEC-35b/SPEC-40c payload hashing and historical ledger capabilities, not first-package resource/render work. It must approve deterministic payload serialization/canonicalization, byte encoding, algorithm/digest representation, hash policy/version storage, and migration/reverification semantics. It is distinct from ULV-D10 content/snapshot/diff/tool-output hashing.

Open owner decision `LED-D02` blocks SPEC-40b2e and every canonical `eventFamily: 'ledger'` producer. It must decide whether ledger-internal maintenance/repair/migration/audit events are needed and, if so, define exact event/phase/lifecycle branches, producer/domain identities, actor/provenance, private row-key boundary, accepted relationships, redaction/failure behavior, deterministic bounds, ordering/dedupe/replay/migration, and fail-open tests. Ordinary storage of other accepted event families remains independent.

Open owner decision `LED-D03` blocks every durable `caused_by` edge. It must define the exact event-type/pointer/domain matrix, which `provenance.confidence` values qualify, pointer/confidence consistency validation, correlated/inferred/unknown evidence handling, duplicate/conflicting causes, and deterministic rejection tests. Accepted refs or hashed historical capabilities prove endpoint identity only, not causal meaning. Indexes and approved non-causal edges may proceed.

Open owner decision `LED-D04` blocks production Slices 35b-35d. It must define exact natural/idempotency keys and unique constraints for every ledger table; event/child transaction boundaries; duplicate/conflict behavior; whether detached retry/defer exists and its queue/item/byte capacities, attempts, backoff, cancellation, shutdown/restart/replay semantics; permanently missing targets; database nonsettlement; terminal fixed diagnostics; and crash/concurrency/source-isolation tests. No inline retry or unbounded deferred work may be implemented. Slice 35a inventory remains independent.

Open owner decision `UEB-D01` blocks SPEC-40a/40b1a and the first Wiki/File packet. It must define exact admission/listener executor item and byte capacities, concurrency and producer/subscriber fairness, enqueue/eviction/drop behavior, cancellation finalizers, per-task event/context/ref retained-byte and lifetime caps, never-settling isolation, and listener saturation behavior. Byte accounting must define measured representation/encoding, object/container overhead, shared-event/context/ref apportionment, queued/active/cancelling ownership, charge/release transition points, cap precedence, and bounded cap-plus-one measurement. Every command has a bounded private owner cell whose atomic `open_empty|open_slot -> closed` transition makes completion/cancel/throw win safely over late installation; initialization failure disables only provenance. UI preflight owns no slot/link until all bounded data is ready; nullable slot failure installs/offers nothing, install after close terminalizes/releases the new slot, and the fixed offer receives a successfully installed slot synchronously while only its D01-created link enters task ownership. D01 must separately define global owner-cell/live-slot count/byte caps, per-slot/per-producer lease caps, repeated acquisition, slot/ref/lease lifetime, and the private nonserializable `AcceptedRefSlotTaskLink` representation/item/byte charge, atomic link-creation/admission-or-finalization transition, single-settlement rule, partial-state release, leaked-cell/link/lease expiry/forced cleanup, slot-registry shutdown, restart, and fixed value-free overload/leak diagnostics. Slot/lease exhaustion returns absent/null and releases bounded provenance state. Link creation/measurement/setup failure, rejection, or overflow invokes only the internal fixed link finalizer, settles an installed slot once, terminates only provenance work, independently skips saturated listener deliveries, and never backpressures or retries a source operation. No queued owner cell/slot handle, caller callback, runnable, finalizer, command-context handle, capacity, accounting, or default is permitted; the packet cannot be assembled, frozen, approved, or handed to an orchestrator until this decision closes and the affected documents are back-validated.

Open owner decision `RSC-D17` blocks SPEC-32b0 token allocation/transport activation and the first Wiki/File packet. It must define exact global/per-connection token-metadata executor queue item/byte caps, concurrency/fairness, enqueue/eviction/drop behavior, cancellation/finalizer deadlines including abort-ignoring providers, per-job retained context/provider byte and lifetime caps, live-token binding count/byte caps and cleanup, shutdown/restart, and fixed value-free saturation diagnostics. Byte accounting must define measured job/binding representation/encoding, object/provider-wrapper overhead, shared-ref apportionment, queued/active/cancelling/live ownership, charge/release points, cap precedence, and bounded cap-plus-one measurement. Capacity failure only omits token metadata and releases bounded state; it never retries or affects init, transitions, panels, prompts, connection lifecycle, or source operations. No capacity/accounting/default is permitted.

Open owner decision `CHAT-D01` blocks SPEC-40b2a canonical chat registration and migration, not first-package resource/render work. It must define exact canonical event types and phase/lifecycle status/presence matrix; IDs, chat payload fields, mirrors, current-record identities, and accepted-only relationships; optional UI cause/result pointer bindings and non-wait behavior; redaction policy ID/version plus sensitive prompt/content/attachment/native-ref handling; failed-redaction safe-core versus no-event behavior; deterministic text/attachment/tool-summary/native-ref/array/serialized-byte bounds and truncation/omission/overflow forms; ordering, dedupe, replay, and idempotence; legacy coexistence/removal/backfill; finding 4's `chatResources` relationship to normalized `resources[]`; finding 8's derivation-versus-redaction-survival rule for `chat.hasToolCalls`; and fail-open tests. Until closure, current `chat:*` facts remain noncanonical, receive no canonical admission marker or `uiActionId`, and are not mutated or backfilled.

Open owner decision `AUT-D02` blocks a file-trigger automation fact from storing `automation.matchedEventId`, upstream resource root/parent/causation IDs, or a direct `triggered` edge. Because the operational watcher filter executes independently of canonical resource admission, D02 must define the private observation/run capability handoff, non-wait ordering, lifetime, exact pointer/selector, multiple-match and rename behavior, dedupe, late/missing/rejected/cancel/restart semantics, and exactly-once tests. Operational triggers continue unconditionally; only after AUT-D03 approves a base canonical automation fact may that fact proceed while omitting D02-blocked resource relationships.

Open owner decision `AUT-D03` blocks base canonical automation run/match registration, emission, accepted references, persistence, and any new production run-ID generator/ABI. The settled requirement is that eventual canonical automation facts contain durable `automation.runId` and `automation.kind`; D03 cannot remove those fields. It must define exact per-kind generation owner/timing/format and operational handoff; event/phase/lifecycle presence; subtype ID ownership/equality/presence; actor/source/origin/observer/context; sensitive trigger/schedule/condition/path fields and redaction policy/failure branch; deterministic bounds/overflow; ordering, dedupe, replay, restart, and cancellation; and fail-open tests. Slices 37a-37b may only audit existing IDs and prepare inert decision tables/ABI fixtures/tests; they cannot add/replace a production generator, expose a new ID ABI, or create canonical identity. AUT-D01 and AUT-D02 remain separate result and matched-resource gates.

Open owner decision `TOOL-D01` blocks SPEC-40b2b `chat.tool.args|result` registration and corresponding persistence, not first-package resource/render work, SPEC-36a evidence gathering, or preparatory harness identity/native-ref work. Jointly with `AUT-D01` and finding 3, it must select the unified captured-output extension contract—including whether it is one shared block—then define exact tool mapping; args/result/outcome domains; normalization/encoding; redaction policy IDs/versions, detection, shapes, omissions, failure-safe/no-event behavior, and safe resource extraction; hash/byte/truncation semantics; exit/signal/provider-error normalization into outcome/lifecycle fields; complete phase/outcome presence; external-artifact qualification without row-ID leakage; bounds and unavailable/partial/stream/error/cancel/timeout branches; and fail-open tests. Finding 4 separately blocks `toolResources` until its relationship to normalized `resources[]` is approved.

Open owner decision `TOOL-D02` blocks canonical harness identity and `chat.tool.started` registration, accepted refs, activation, and persistence. It must define exact event/phase/lifecycle presence; current-record harness/tool ID ownership/equality; actor/source/origin/observer; provider/native-ref allowlist and redaction policy/failure branch; deterministic bounds/overflow; ordering, sequence, dedupe, replay, reconnect, cancel; accepted-only chat/upstream relationships; and fail-open tests. Slices 36a-36c remain inert evidence/helpers.

Open owner decision `AUD-D01` blocks SPEC-40b2f audit-domain registration and SPEC-38b-38f, not first-package resource/render work or SPEC-38a evidence gathering. It must define exact versioned query/review/recommendation/ticket schemas and domain ownership; event/phase/lifecycle branches; typed/redacted filters; confidence and completed/failed/incomplete/unavailable/cancel semantics; accepted evidence/result presence; redaction policy/failure-safe behavior; deterministic hard filter/evidence/result/summary/recommendation/ticket/traversal/serialized-byte bounds, overflow diagnostics and pagination; and fail-open tests.

Open owner decision `ULV-D04` blocks storm detection, batch persistence, and compaction. It covers exact window/group/quiet thresholds; global active-window/workspace/key/member/timer/diagnostic/reconciliation/in-memory capacities; hard capacities for every persisted storm array, summary, edge, batch row, diagnostic, and serialized byte budget; deterministic admission/coalescing/eviction/expiry/cleanup/selection/deduplication/truncation; first/last preservation; overflow counters/flags and follow-up discoverability; crash/restart semantics; byte measurement; cap precedence; and configuration ownership. Unique-key/sustained-load overflow cannot suppress or delay source facts, drop artifacts before accepted 35f, or create false attribution. No implementation may invent defaults or call either detector or summary bounded before approval.

`ULV-D03` and `ULV-D05` also block metadata/hash-only file-version rows, not only content artifacts or storms. D03 must decide eligibility for any row across file type/size/class and metadata-only exclusions; D05 must decide retention/deletion for metadata rows, edges, and indexes as well as snapshots/diffs/blobs. Non-batch metadata/hash-only registration/emission additionally requires `ULV-D10` and `ULV-D12`; content persistence has its further named blockers.

## Direct WebSocket Broadcasts Are Derived Output

Server file APIs can still send command acknowledgements to clients, but cache invalidation should flow from canonical resource events through a resource-sync broadcaster.

Direct `file_changed`-style broadcasts are not a durable compatibility contract. Existing paths should be audited and replaced thoroughly because the app is not in production. Temporary legacy adapters may span the resource-sync migration window, but should be removed before the server mutation producer normalization slice is complete.

The only fail-open freshness transports are the non-canonical `FreshnessRecoveryMessage` union: `resource:refresh_required` for mutation/watcher failures and `lifecycle:refresh_required` for workspace/view-registry/theme failures. Pre-admission candidate rejection/throw/suppression exposes no ref/delivery; post-admission projection failure preserves the accepted ref/frozen event for other subscribers. Clients preserve navigation/history/scroll/dirty/optimistic/undo state; clean entries replace and dirty entries use `recoveryRemote`/`conflict_pending`. Reconnect cannot claim false freshness. Recovery never feeds canonical subscribers.

Renderer cache invalidation should use a transport-specific message such as `resource:invalidate`, not reuse canonical resource event identity for `resource:*` bus-topic or WebSocket/cache semantics.

First-package lifecycle publication is connection-originated; headless/global lifecycle routing is not registered. Its private route sidecar includes opaque connection and lifecycle-epoch capabilities. Delivery and recovery recheck that the initiator still has the captured epoch/workspace, so a queued obsolete transition cannot clear or rewarm newer client state. Stale or missing routing state affects only renderer freshness work and never canonical admission or the source operation. Connection or epoch identity is never canonical metadata or ledger content.

Before canonical `workspace:switched` is enabled, SPEC-32b0 atomically moves the active operational transport to permanent private `workspace:operational_switched`, installs coordinator-authoritative workspace/root resolution plus cache-only session projection and synchronous baseline broadcaster recovery, removes workspace switching from the old ledger whitelist, and proves all other old-shape paths are moved or fenced. Healthy baseline renderer notification is exactly one; failure is at-most-once and converges through authoritative reconnect snapshot/recovery. This noncanonical, unpersisted transport is not awaiting a provenance retirement slice. Canonical lifecycle separately drives accepted-only facts and `resource:invalidate`. Neither bus shape may enter the other's broadcaster/subscribers, and canonical lifecycle persistence waits for SPEC-35.

The first-package producer data/schema artifact is the single source for exact producer tokens, handler/event/source/observer permissions, command lease roles, and workspace producer/reason pairs. Every artifact entry is required by the declared package and must be active by 40b1b; there is no separate enabled state. Every owning slice re-probes and promotes its entries before acceptance. Planned entries grant no runtime permission. A `planned -> active` promotion atomically regenerates active-only authorization tables without changing `freezeVersion` only when intended semantic fields are unchanged; evidence-only updates change neither permission nor version. Any handler/event/reason/source/observer/lease/command semantic change increments `freezeVersion` and atomically updates generated 40a token and 40b1a validator support. Mismatch disables only affected provenance, never the operation. The 40b1b integration gate rejects any planned, stale, or drifting entry.

## Canonical Resource Events Precede Render Projections

Resource mutation events should use the shared provenance envelope and `resourceMutation` domain payload. Render/resource sync can derive a smaller projection for cache invalidation, but that projection is not the canonical event and must not become a second event language.

The canonical event must preserve event identity, workspace/resource identity, `ids`, `actor`, `provenance`, `context`, `resources[]`, and enough before/after metadata for future versioning subscribers.

Create, modify, delete, rename, and metadata resource events should include explicit before/after-capable state, or an explicit omission reason when state is unavailable. Deletes need prior state plus `after.exists = false`; creates need `before.exists = false`; renames need old and new path/parent context.

## Automation Uses Durable Run Identity

Automation events use `automation.runId` and `automation.kind`; these two common-field requirements are settled, while AUT-D03 owns their exact generation ABI and all subtype ID ownership/equality/presence. Downstream resource events may reference the common identity through `provenance.cause.automationRunId` and, when approved for that event schema, compact `automationRef.automationRunId` / `automationRef.automationKind`, only from an accepted automation reference. Subsystem-specific IDs such as `triggerRunId`, `schedulerRunId`, `scriptRunId`, or `agentRunId` remain D03 candidates rather than settled secondary indexes.

## High-Frequency Changes Need Storm Control

The ledger must eventually compact or summarize high-iteration file changes so a runaway script, trigger, formatter, or watcher loop cannot flood durable history or future assistant context.

Storm control belongs in ledger/versioning subscribers. Event producers should still preserve enough facts for subscribers to decide what to compact.

Storm records should use the shared event envelope and preserve time range, affected paths, count, and representative safe metadata when available. Any embedded member cause/actor/resource ID requires an exact SPEC-39 target/source `acceptedPayloadPointer` builder binding against a live accepted ref or revalidated historical capability; whole-object copying is forbidden. Mixed-cause or mixed-actor storms omit a single top-level cause/specific actor and use separately proven summary entries. Representative hashes/snapshot/diff references require their later approved policies.

The first slice that persists storm batches treats them as `eventFamily: 'file.version'`, `eventType: 'file.version.change_batch'`, with storm details under a `changeStorm` domain payload. This can be promoted to a separate storm family later only by explicit decision.
