# CHAT-AR integration and retirement — intake and return point

> Prepared scope and source pointers; not an executable roadmap or implementation approval.

## Assignment

Owner transfer recorded 2026-09-28 UTC: “Let's transfer your responsibilities here: /Users/rccurtrightjr./projects/fs-dev/ai/RC-MacAir-15/mission-control/launchpad/chat-integration-and-retirement/”. This folder is now the canonical working-memory home for the remaining chat integration, retirement, applicable verification and consumer handoff previously coordinated in supervisor task `01a0c1c8-6e85-7f83-8d67-2cb5c1476007`. Read D-002 and the transferred synthesis in CAPTURE. This is a responsibility/document handoff, not a new task dispatch, app CWD change or checkpoint registration.

The owner approved a distinct Launchpad folder for this subject in the current Mission Control setup conversation, after coordination with [Run roadmap supervisor](codex://threads/01a0c1c8-6e85-7f83-8d67-2cb5c1476007). Source direction: [SPEC-06 closure addendum](../../../Captures/035-Composer_Typing_Regression/ROADMAP/SPEC-06-OWNER-CLOSURE-ADDENDUM.md); supporting context: [CHAT-AR ledger](../../../Captures/035-Composer_Typing_Regression/ROADMAP/ROADMAP-LEDGER.md) and [SPEC-06](../../../Captures/035-Composer_Typing_Regression/ROADMAP/SPEC-06.md). No main task is registered for this folder.

## Desired outcome

Give later plugin and view work an exact, reviewed chat source/build baseline, a contract map, actual retirement findings, and honestly scoped verification.

## Scope and dependencies

SPEC-06 remains owner-accepted with residuals. This folder does not reopen its acceptance. Ongoing bookmarks, unrelated dogfood reports, logger design, and new health-event subscriptions belong in the [health folder](../fusion-health-and-governed-observability/TICKET.md). The work may be shaped alongside sibling folders, but a dependency is released only by a named, reviewed contract or accepted integration result. The owner will settle detailed scope and sequencing after provisioning.

## Current disposition

D-006’s managed First Draft is independently validated for discussion, with no material draft findings. See [FIRST-DRAFT](planning/chat-transport-simplification/FIRST-DRAFT.md), [stage report](planning/chat-transport-simplification/reports/STAGE-REPORT.md) and REF-013. The proposed sequence is transport decomposition → unified sends → status-send result handling. R1–R4 are bounded Creator work; no new owner product decision is required for that handoff. Source artifacts remain linked, and no executable product candidate or consumer release is approved by this draft. See [INTENT](INTENT.md), [DECISIONS](DECISIONS.md), [ISSUES](ISSUES.md), and [REFERENCES](REFERENCES.md).

Supervisor handoff is incorporated here. The setup coordinator was inspected idle before this update; there is no conflicting writer identified. SPEC-06 remains accepted. Latest owner-requested development preview was rebuilt/launched successfully; its two processes and server connection were observed still present at 2026-09-28 06:26 UTC. That is startup evidence, not a Diagnostics UI or integrated product certification. Details and limits are in CAPTURE/REF-005. Leave the owner's preview running.

A 2026-09-28 06:57 UTC read-only comparison found 1,993/1,997 RD-02 accepted source paths and all 200 build paths still matching; the four source differences and two unlisted fixture additions are recorded in CAPTURE/REF-006. Checked client/server product-source trees match the accepted listed bytes. Initial retirement inspection identified live open/history compatibility paths for bounded reachability review (I-005) and a source-confirmed Side Chat control gap that affects later view consumers (I-006). No new product verification or retirement completion is claimed.

D-003 waives the historical 45-minute soak as this folder's exit requirement. The owner is currently debugging an accepted-message/no-response warning in the development app. Four live receipts from 06:51–06:52 UTC show `provider_failed` after acceptance and dispatch claim; the exact exception is not yet visible in current logs. See I-007/REF-007. Keep the running app state available for diagnosis.

Two owner-requested read-only investigations returned at 07:40–07:42 UTC (REF-008). They narrowed I-007 to a failure after durable acceptance and dispatch claim; `wire_ready` does not certify that OpenCode's per-turn child launched. Current logs cannot distinguish spawn, early exit, session-ID persistence or another pre-output error. The 167 MB database is chiefly historical event data, and the observed ~16,100 post-incident file descriptors have no proven causal link. A separate source-backed recovery gap (I-008) can leave status ambiguous and may hide an accepted prompt after a fresh renderer load; the latter needs an affected route check. The prior Side Chat and compatibility findings remain I-006 and I-005. Computer Use again returned `-10005`, so no on-screen inspection is claimed.

The owner then authorized temporary logs pending the governed subscriber, with explicit removal/migration annotation. Content-free `temp_chat_boundary_v1` diagnostics are implemented in the development checkout and 160 initial focused tests passed (REF-009). At 08:18 UTC after the first restart, a recurrent failure was captured as synchronous OpenCode `spawn_throw` before PID return; the exact exception was outside the first closed classifier (REF-010). The owner also reported force reloading Electron both times, without established causal link. The classifier was expanded and 61 focused tests passed. A second development restart at 08:24 UTC loaded it on port 51629; a later 08:26 turn launched and closed normally, so the expanded classifier still awaits a failed send. The code comment names the future health subscriber as the migration or deletion point.

At 08:28–08:31 UTC the owner reported a broken “Checking delivery status” display and thread clicks that did not open. No new durable receipt was found in the inspected interval, though the unknown request ID prevents exact attribution (I-009/REF-011). Temporary traces now cover prompt, receipt-status and thread-open routing as well as the child boundary. The owner saved the draft and approved another dev restart, completed at 08:40 UTC on port 51857; 13 focused tests and the client build passed. Source review found the new Diagnostics display samples every 200 ms only while mounted and its server subscription flushes every 100 ms, with cleanup and capped text/event queues. Diagnostic tabs start empty after restart. Renderer PID 77021 rose from about 1.27 GB to a 2.67 GB RSS peak within two minutes, then fell to about 1.50 GB by four minutes; memory attribution remains open (I-010), and an accumulating leak has not been established. No timed soak has been reinstated.

The owner requested a source-based modularity check at 22:05 UTC. REF-012 finds substantial alignment in server-owned runtime/adapters and focused host composition, but I-011 records transport routers with mixed responsibilities, repeated direct chat socket sends, a discarded false-send result in receipt recovery, and a qualified provider-specific presentation seam. Full compliance with the stated one-job-per-file and portability goals is not certified. This read-only assessment does not identify the live incident's root cause or authorize a broad refactor.

Latest owner direction (D-004/D-005): prepare a First Draft around three simple candidates—two transport entry files, unified chat command send behavior, and the false-send status-check seam. Park the full Fusion/OpenCode send/execution/UI failure map in a separate task to resume only after the three-candidate First Draft → Roadmap → Build → owner approval sequence. Existing I-007/I-008/I-009 evidence and the temporary diagnostic removal/migration marker remain available; their broader recovery redesign is outside this draft unless a concrete dependency is shown.

The old supervisor conversation is a historical source, not a second live task ledger. Product evidence and acceptance receipts remain in their original capture paths. Health issue I-001 already points to this folder; no second copy needs to be created. Future domain-session registration, if needed, uses the supported procedure separately; no cursor was created or advanced by this transfer.

## Next safe action

D-007 now authorizes Roadmap Creation. The active supervisor uses [Roadmap coordination](planning/chat-transport-simplification/roadmap/PLANNING.md) to manage candidate creation, independent stage/release validation and the final owner approval checkpoint. The reviewed draft/preparation steps below are completed prerequisites; do not repeat them without changed evidence.


Use the reviewed three-candidate draft and its independent validation to prepare Roadmap Creation. The supervisor completes a fresh document sweep and inline roadmap-creation preflight; the resulting preparation report belongs at `planning/chat-transport-simplification/ROADMAP-PREP.md`. Creator then resolves R1–R4 before executable release. The bounded deferral assessment supports retaining I-007/I-008/I-009 repair options under the draft constraints; recheck actual planned changes and hold only an affected candidate/consumer if those options would be lost. Preserve active content-free traces for a later affected send and keep their future delete/migrate obligation visible. Shape affected checks without the historical 45-minute soak. Before any execution assignment, record its exact source revision, writer, report destination, verification and owner checkpoint. Mission Control and its recurring loop remain inactive.

Do not resume the old SPEC-06 soak chain or reopen acceptance by default. First identify the actual delta and any residual whose repair would become harder under plugin/view changes; bring only that consequential choice to the owner. No implementation is dispatched by this transfer. Documentation handoff review state is retained in .document-sweeps/.
