'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

describe('screenshot generated-file protected view boundary', () => {
  let root;
  let canonicalRoot;
  let consoleErrorSpy;
  let consoleWarnSpy;

  beforeEach(() => {
    jest.resetModules();
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'fusion-screenshot-protection-'));
    process.env.FUSION_LOCAL_MACHINE = 'Test-Machine';
    process.env.FUSION_FOCUS_STATE_PATH = path.join(root, 'focus.json');
    fs.writeFileSync(process.env.FUSION_FOCUS_STATE_PATH, '{"focused":true}', 'utf8');
    canonicalRoot = path.join(root, 'ai', 'Test-Machine', 'System', 'Views', '001-files');
    fs.mkdirSync(canonicalRoot, { recursive: true });
    fs.writeFileSync(path.join(canonicalRoot, 'content.json'), 'protected', 'utf8');
    const screenshotParent = path.join(root, 'ai', 'Test-Machine', 'Data');
    fs.mkdirSync(screenshotParent, { recursive: true });
    fs.symlinkSync(canonicalRoot, path.join(screenshotParent, 'Screenshots'), 'dir');

    jest.doMock('../lib/workspace/workspace-controller', () => ({
      getActiveWorkspaceSync: jest.fn(() => ({
        id: 'workspace-a', repo_path: root,
      })),
      listWorkspaces: jest.fn(async () => []),
    }));
    consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
    consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    consoleErrorSpy.mockRestore();
    consoleWarnSpy.mockRestore();
    delete process.env.FUSION_LOCAL_MACHINE;
    delete process.env.FUSION_FOCUS_STATE_PATH;
    fs.rmSync(root, { recursive: true, force: true });
    jest.resetModules();
  });

  test('public file capture denies a symlink alias before writing generated bytes', async () => {
    const createScreenshotHandlers = require('../lib/screenshot/ws-handlers');
    const ws = {
      sent: [],
      send(message) { this.sent.push(JSON.parse(message)); },
    };
    const handlers = createScreenshotHandlers({ getAllClients: () => [] });

    await handlers['screenshot:file-capture'](ws, {
      type: 'screenshot:file-capture',
      workspaceId: 'workspace-a',
      requestId: 'protected-capture',
      dataUrl: 'data:image/png;base64,aW1hZ2U=',
    });

    expect(fs.readdirSync(canonicalRoot)).toEqual(['content.json']);
    expect(ws.sent).toEqual([expect.objectContaining({
      type: 'screenshot:error', requestId: 'protected-capture',
    })]);
  });

  test('ordinary direct screenshot capture remains functional and correlated', async () => {
    const screenshotDir = path.join(root, 'ai', 'Test-Machine', 'Data', 'Screenshots');
    fs.unlinkSync(screenshotDir);
    fs.mkdirSync(screenshotDir);
    const createScreenshotHandlers = require('../lib/screenshot/ws-handlers');
    const ws = {
      sent: [],
      send(message) { this.sent.push(JSON.parse(message)); },
    };

    await createScreenshotHandlers({ getAllClients: () => [] })['screenshot:file-capture'](ws, {
      type: 'screenshot:file-capture',
      workspaceId: 'workspace-a',
      requestId: 'direct-capture',
      dataUrl: 'data:image/png;base64,aW1hZ2U=',
    });

    expect(ws.sent).toEqual([expect.objectContaining({
      type: 'screenshot:file-captured', requestId: 'direct-capture',
    })]);
    expect(fs.readdirSync(screenshotDir)).toEqual([expect.stringMatching(/^fusion-capture-.*\.png$/)]);
  });

  test('public file capture denies a broken final symlink into a protected tree', async () => {
    jest.useFakeTimers().setSystemTime(Date.parse('2026-01-02T03:04:05Z'));
    const saveId = '00000000-0000-4000-8000-000000000001';
    const randomUUIDSpy = jest.spyOn(require('crypto'), 'randomUUID').mockReturnValue(saveId);
    try {
      const screenshotDir = path.join(root, 'ai', 'Test-Machine', 'Data', 'Screenshots');
      fs.unlinkSync(screenshotDir);
      fs.mkdirSync(screenshotDir);
      const generatedPath = path.join(screenshotDir, `fusion-capture-2026-01-02T03-04-05-000Z-${saveId}.png`);
      const protectedFutureFile = path.join(canonicalRoot, 'future.png');
      fs.symlinkSync(protectedFutureFile, generatedPath);
      const createScreenshotHandlers = require('../lib/screenshot/ws-handlers');
      const ws = {
        sent: [],
        send(message) { this.sent.push(JSON.parse(message)); },
      };

      await createScreenshotHandlers({ getAllClients: () => [] })['screenshot:file-capture'](ws, {
        type: 'screenshot:file-capture',
        workspaceId: 'workspace-a',
        dataUrl: 'data:image/png;base64,aW1hZ2U=',
      });

      expect(fs.lstatSync(generatedPath).isSymbolicLink()).toBe(true);
      expect(fs.existsSync(protectedFutureFile)).toBe(false);
      expect(ws.sent).toEqual([expect.objectContaining({
        type: 'screenshot:error', message: 'Protected view path',
      })]);
    } finally {
      randomUUIDSpy.mockRestore();
      jest.useRealTimers();
    }
  });
});
