"""Assemble explicit raw full-S6 navigation; no review result is asserted."""
import json,os
import readbacks as q
E,J,O,C,R=q.E,q.J,q.O,q.C,q.R
def load(p):return json.loads(q.Path(p).read_bytes())
def record(p):
 p=q.Path(p);assert p.exists(),p
 return {'path':str(p.resolve()),**q.leaf(p)}
def rows(base,names):return [record(base/n) for n in names]
definitions=load(E/'S6-review-criterion-definitions.json')
frozen=load(E/'S6-prep/prep-freeze.json')
prep_raw={k:frozen[k] for k in ['kind','frozen_at','builder','root_inherited_settings','controller_home','candidate','dependencies','candidate_exact_leaves']}
prep_raw['owned_files']=[r for r in frozen['owned_files'] if not any(t in r.get('path','') for t in ['S6-builder.md','review','report-only','frozen-provisional-builder'])]
prep_raw['source_frozen_sha256']=q.sha((E/'S6-prep/prep-freeze.json').read_bytes())
prep_raw['omitted']='Own prep report/prior outer review/report-finalization navigation omitted; raw capture dependencies and exact candidate fingerprints retained'
q.save(O/'preparation-raw-fingerprints.json',prep_raw)
evidence={
'S6-A01':rows(E,['S6-prep/private-paths.json'])+rows(O,['preparation-raw-fingerprints.json']) if (E/'S6-prep/private-paths.json').exists() else [],
'S6-A02':rows(J,['activation.json','activation-intent.json','activation-first-candidate.json','activation-fix-xy.json','negative-control-1/activation.json','interruption-1/activation.json','recovery-1/activation.json']),
'S6-A03':rows(J,['provider-hold.json','provider-hold-report.md','evidence/intent-release-validation.json']),
'S6-A04':rows(J,['intent-hold.json','intent-hold-report.md','evidence/first-release-reconciliation.json']),
'S6-A05':rows(J,['reviews/initial-reviewer-1.raw.md','reviews/initial-manager-1.md','reviews/initial-manager-1-lifecycle.json']),
'S6-A06':rows(J,['workers/code-repair-1.md','evidence/first-code-command-only.json','reviews/code-handoff-1-error.raw.json','reviews/code-handoff-2.raw.md','reviews/code-handoff-3.raw.md','evidence/first-code-handoff-acceptance.json']),
'S6-A07':rows(J,['workers/wiki-repair-1.md','workers/wiki-repair-1-commands.json','evidence/first-wiki-version-selection.json','evidence/first-wiki-union-capture-command.json','recovery-supplements/first-wiki-1/recovery/manifest.json']),
'S6-A08':rows(J,['reviews/wiki-handoff-1.raw.md','evidence/first-wiki-handoff-acceptance.json','evidence/first-wiki-command-only.json']),
'S6-A09':rows(J,['evidence/first-final-identity.json','reviews/final-reviewer-1.raw.md','reviews/final-manager-1.md','reviews/final-manager-1-lifecycle.json','evidence/fix-xy-python-current-2-bindings.json','evidence/fix-xy-node17-current-bindings.json']),
'S6-A10':rows(J,['evidence/first-canonical-runtime-command.json','evidence/first-runtime-raw-files.json','evidence/first-current-runtime-identity.json','evidence/fix-xy-canonical-runtime-command.json','evidence/fix-xy-current-runtime-identity.json','evidence/fix-xy-runtime-raw-files.json']),
'S6-A11':rows(J,['evidence/first-restart-checked-precondition.json','evidence/first-preinitializer-reset.json','evidence/first-preinitializer-reset.json.png','evidence/first-ui-acceptance.json','evidence/first-ui-acceptance.json.png','evidence/fix-xy-pre-restart-checked.json','evidence/fix-xy-preinitializer-reset.json','evidence/fix-xy-ui-acceptance.json','evidence/fix-xy-ui-acceptance.json.png']),
'S6-A12':rows(J,['evidence/first-watcher.json','evidence/first-watcher-command.json','evidence/fix-xy-watcher.json','evidence/fix-xy-watcher-command.json','evidence/first-node-suite-command.json']),
'S6-A13':rows(J,['owner-packet-first.md','first-candidate-report.md','evidence/first-owner-evidence-index-final.json','lifecycle-first-candidate.json']),
'S6-A14':rows(J,['fix-xy-original-authority.md','workers/fix-xy-code-1.md','evidence/fix-xy-code-command-only.json','reviews/fix-xy-code-handoff-1.raw.md','workers/fix-xy-wiki-1.md','evidence/fix-xy-wiki-command-only.json','reviews/fix-xy-wiki-handoff-1.raw.md','reviews/fix-xy-final-manager-1.md','reviews/fix-xy-final-manager-2.md','reviews/fix-xy-final-manager-3.md','reviews/fix-xy-final-reviewer-3.raw.md','reviews/fix-xy-final-manager-3-lifecycle.json','evidence/fix-xy-python-current-2-bindings.json','evidence/fix-xy-node17-current-bindings.json','evidence/fix-xy-runtime-acceptance.json','owner-packet-fix-xy.md','supervisor-fix-xy-report.md','lifecycle-fix-xy.json']),
'S6-A15':rows(J,['negative-control-1/report.md','negative-control-1/inspection.json','negative-control-1/zero-observer-mutation-proof.json','negative-control-1/protection-comparison.json']),
'S6-A16':rows(J,['interruption-1/checkpoint.json','interruption-1/report.md','interruption-1/fixed-checkpoint/recovery/manifest.json','recovery-1/checkpoint.json','recovery-1/report.md','recovery-1/criterion-map.json','recovery-1/all-raw-command-receipts.json','recovery-1/actual-restore-order.json','recovery-1/original-full-exact-readback.json','recovery-1/final-preservation-proof.json']),
'S6-A17':rows(J,['interruption-1/final-preservation-proof.json','recovery-1/final-preservation-proof.json','recovery-1/after-original.json','recovery-1/lifecycle.json'])+rows(O,['before.json','ownership-and-preimages.json','write-receipt.json']),
'S6-A18':rows(O,['ownership-and-preimages.json','write-receipt.json'])+rows(C,['AGENTS.md','todo.md','registry.md','handoff.md','deployment.md','skills-and-agents.md'])+[record(q.PAGE)],
'S6-A19':[]}
# Supplement only explicit raw controls; no manager assessment files are inputs.
for criterion,names in {'S6-A03':['S6-provider-release.json'],'S6-A04':['S6-intent-resolution.json'],'S6-A14':['S6-fix-xy-event.json'],'S6-A15':['S6-negative-controls/restored.json']}.items():evidence[criterion]+=rows(E,names)
evidence['S6-A01']+=rows(J,['recovery/manifest.json','evidence/authority-readset.json','evidence/intent-entry-verify.json'])+rows(O,['preparation-raw-fingerprints.json'])
criterion_rows=[{**d,'raw_navigation':evidence[d['id']],'qualification':'Separate root full-S6 and whole-SPEC gates pending; outside this builder-owned gate' if d['id']=='S6-A19' else 'Derive requirements first; these raw paths are test artifacts, not outer acceptance'} for d in definitions['criterion_definitions']]
q.save(O/'criterion-map-v2.json',{'kind':'RAW_REQUIREMENT_TO_ARTIFACT_MAP_NO_VERDICT','original':definitions['original_authority'],'original_sha256':definitions['original_authority_sha256'],'criteria':criterion_rows,'original15_mapping':definitions['ledger_mapping'],'current_state_qualification':'Historical fixed app/gates/two owner waits remain historical. Current private preview stopped, original seeded code restored. Original authority-preservation claims predate explicitly owned six central/article edits.'})

# Record native lifecycle fields without manager assessments or judgments.
ledger=load(E/'S6-runtime-actor-ledger.json')
keep={'identity','requested_type','runtime_agent_type','role','phase','fork_turns','settings','state','dispatched_at','dispatch_observed_at','acknowledged_at','acknowledgment','terminal_return','terminal_observed_at','close_agent','native_terminal'}
actors=[{k:v for k,v in r.items() if k in keep} for r in ledger['actors']]
q.save(O/'actor-tree-v2.json',{'kind':'NATIVE_LIFECYCLE_FIELD_EXTRACTION_NO_OUTER_ASSESSMENT','source_sha256':q.sha((E/'S6-runtime-actor-ledger.json').read_bytes()),'actors':actors,'domain_descendant_raw_paths':rows(J,['evidence/first-actual-actor-tree.json','evidence/fix-xy-actual-actor-tree.json','lifecycle-first-candidate.json','lifecycle-fix-xy.json','reviews/initial-manager-1-lifecycle.json','reviews/final-manager-1-lifecycle.json','reviews/fix-xy-final-manager-1-lifecycle.json','reviews/fix-xy-final-manager-2-lifecycle.json','reviews/fix-xy-final-manager-3-lifecycle.json']),'actual_depth':3,'root_settings':'Inherited without overrides; exact loader/model/effort numeric metadata not exposed','closure':'close_agent unavailable; native terminal disposition retained','preparation_actor':'/root/s6_builder, preparation-only report separate; old own prep reviewer not reused for full-S6 gate'})

# Carry every factual deviation field, remove prior conclusions, fill explicit impact.
raw_deviations=[E/'S6-prep/deviations.json',J/'first-deviations.json',J/'fix-xy-deviations.json',J/'negative-control-1/deviations.json',J/'interruption-1/deviations.json',J/'recovery-1/deviations.json']
neutral=[]
for path in raw_deviations:
 value=load(path); entries=value if isinstance(value,list) else value.get('entries',value.get('deviations'))
 for row in entries:
  item={k:v for k,v in row.items() if not any(t in k.lower() for t in ['classification','disposition','assessment','verdict'])}
  item['raw_source_hash']=q.sha(path.read_bytes())
  item['downstream_impact']=item.get('downstream_impact',item.get('downstream_consumer_impact','Retain the stated limits and exact raw provenance at separate full-S6/whole-SPEC acceptance; no publication authority supplied.'))
  item['builder_proposed_classification']='downstream_impact' if any(t in str(item).lower() for t in ['unexposed','incomplete','exposure','volatile','omission','truncated']) else 'accepted'
  neutral.append(item)
neutral.extend([
{'id':'S6-CLOSEOUT-D1','original_criterion':'S6 final deployment/MC-T09 facts and source-correct documentation; expected product paths are advisory','actual_change':'Six current central record surfaces and exact canonical restart PAGE + one exclusive complete-preimage version; former undispatched S4 article author scope assigned to S6 closeout','reason_authority':'Active bounded root closeout assignment and S6-closeout-wiki-ownership contract; no product/helper/test/fixture/runtime behavior expansion','files':[str(p) for p in q.DOCS]+[load(O/'ownership-and-preimages.json')['future_exclusive_version']],'observable_effect':'Current setup continuation and article match installed code/actual bounded rehearsal; historical S5 observations retained','checks':'Complete preimages, gray-matter/schema/source/link/index/H2/whitespace and unowned readback; fresh own full-S6 gate','risk':'Old165/168 authority snapshots are historical through precloseout; source preservation excludes these exact later authorized edits only','downstream_consumer':'Root full-S6 acceptance, final whole-SPEC gate, owner setup acceptance','downstream_impact':'Documentation integration does not invalidate unchanged implementation or historical behavioral raw outputs; affected current documentation reviewed separately','builder_proposed_classification':'accepted'},
{'id':'S6-CLOSEOUT-D2','original_criterion':'Use exact current source paths and bounded inspection','actual_change':'Read-only discovery initially named absent review-gate/runtime-module/adjacent/standards paths; actual paths discovered and full required reads completed','reason_authority':'Routine path lookup correction; no absent source treated as evidence','files':[],'observable_effect':'Failed read diagnostics only, followed by exact canonical five files and actual Wiki/standards instructions','checks':'Current file inventory, complete corrected reads and source hashes','risk':'Failed reads prove no source coverage; corrected reads supply coverage','downstream_consumer':'Fresh own/root reviewers','downstream_impact':'No changed candidate or waived required read','builder_proposed_classification':'downstream_impact'},
{'id':'S6-CLOSEOUT-D3','original_criterion':'Preserve bounded complete evidence and avoid large inventory dumps','actual_change':'Several concatenated metadata/report reads exceeded output budget; switched to exact selected fields, smaller reads and programmatic full comparisons','reason_authority':'Tool output-scoping correction','files':[],'observable_effect':'Transient truncated output, no source mutation','checks':'Saved full raw local records; completed exact source and all-record hash comparisons','risk':'Truncated output alone is not coverage proof','downstream_consumer':'Fresh own/root gates','downstream_impact':'Review uses explicit raw file navigation and complete current manifest','builder_proposed_classification':'downstream_impact'},
{'id':'S6-CLOSEOUT-D4','original_criterion':'Read Git without optional locks and preserve physical source index','actual_change':'Initial revision/status orientation omitted GIT_OPTIONAL_LOCKS=0; all subsequent own Git wrappers strip inherited GIT_* and set optional locks/literal paths','reason_authority':'Disclosed procedural omission; revision/stat reads only','files':[],'observable_effect':'Source physical index observed unchanged at f37b5bfc9a44893b132661290fe095ddafccb79bed38ca9007dc3803d2ff7966','checks':'Historical original hash and current full index/status/stage/ref/cache readbacks','risk':'Cannot retroactively change initial invocation environment','downstream_consumer':'Root procedural classification','downstream_impact':'No observed state effect; inherited publication gates intact','builder_proposed_classification':'downstream_impact'},
{'id':'S6-PREP-D13','original_criterion':'Preserve frozen preparation report provenance during terminal report-only append','actual_change':'Exact hash-verified immutable provisional bytes reconstructed after terminal metadata append; timing explicitly recorded','reason_authority':'Root expressly authorized provenance housekeeping only','files':[str(E/'S6-prep/frozen-provisional-builder-preimage.md'),str(E/'S6-prep/report-only-finalization.json')],'observable_effect':'Old a6be0229 frozen report bytes preserved independently; current preparation report remains preparation only','checks':'Exact frozen SHA match and postappend metadata-only diff/raw receipt','risk':'Reconstruction occurred after append; no invented earlier-copy timestamp','downstream_consumer':'Full-S6 provenance','downstream_impact':'No candidate/helper fixture repair or repeated prep gate','builder_proposed_classification':'accepted'}])
q.save(O/'deviations-neutral-v2.json',{'kind':'FULL_FIELD_FACTS_WITH_BUILDER_PROPOSALS_NO_PRIOR_CLASSIFICATIONS','deviations':neutral,'classification_owner':'Root separately; proposals do not bind owner','historical_raw_source_hashes':{str(p):q.sha(p.read_bytes()) for p in raw_deviations}})

# Current authority and all raw domain files. Explicit path inventory; no broad evidence glob instructions.
authority=[C/'session-contract.md',C/'decisions.md',C/'index.json',R/'AGENTS.md',C/'planning/commit-supervisor/SPEC.md',E/'approval-receipt.md',E/'S6-review-criterion-definitions.json',C/'.agents/skills/mc-spec-slice-builder/SKILL.md',C/'.agents/skills/mc-spec-review-gate/SKILL.md',C/'.codex/agents/mc-spec-slice-builder.toml',C/'.codex/config.toml']
for folder in [C/'.agents/skills/mc-commit-supervisor',C/'.agents/skills/mc-code-review-orchestrator',C/'.agents/skills/mc-commit-repair-worker']:
 authority += [p for p in sorted(folder.rglob('*')) if p.is_file() and '__pycache__' not in p.parts]
authority += [C/'.codex/agents'/n for n in ['mc-commit-supervisor.toml','mc-code-review-orchestrator.toml','mc-commit-repair-worker.toml']]
authority += [q.W/'AGENTS.md',q.W/'.agents/wiki-session-contract.md']+[p for p in sorted(q.W.rglob('SKILL.md')) if any(t in str(p) for t in ['research','repair','audit'])]
authority += [p for p in sorted((q.W/'005-Enforcement/001-Code_Standards').rglob('PAGE.md'))]
authority += [q.W/n for n in ['000-Wiki_Guidance/001-Style_Guide/PAGE.md','000-Wiki_Guidance/003-Updating_Wikis/PAGE.md','000-Wiki_Guidance/004-Audit_Workflow/PAGE.md']]
authority += [R/n for n in ['restart-fusion.sh','scripts/fusion-restart.mjs','scripts/fusion-restart-target.mjs','scripts/fusion-restart-processes.mjs','scripts/fusion-restart-probe.mjs']]
authority += [q.Path('/Users/rccurtrightjr./.codex/skills/fusion-electron-restart/SKILL.md')]
preferences=[q.W/'000-Wiki_Guidance/005-User_Profile_Preferences_and_Design_Philosophy/PAGE.md']
authority += preferences
sources=rows(O,['criterion-map-v2.json','actor-tree-v2.json','deviations-neutral-v2.json','before.json','ownership-and-preimages.json','write-receipt.json'])
domain=[record(p) for p in sorted(J.rglob('*')) if p.is_file() or p.is_symlink()]
q.save(E/'S6-closeout-manifest.json',{'schema':1,'kind':'CURRENT_FULL_S6_RAW_MANIFEST_NO_OUTER_VERDICT','at':q.now(),'actor':'/root/s6_builder','scope':'Full S6 behavioral evidence + bounded factual closeout; separate root and whole-SPEC gates pending','authority':list({r['path']:r for r in map(record,authority)}.values()),'changed_documentation':[record(p) for p in q.DOCS]+[record(load(O/'ownership-and-preimages.json')['future_exclusive_version'])],'closeout_raw':sources,'criteria_map':str(O/'criterion-map-v2.json'),'actor_tree':str(O/'actor-tree-v2.json'),'deviations':str(O/'deviations-neutral-v2.json'),'actual_domain_raw':domain,'domain_reports_policy':'Actual installed workflow domain reports are behavioral test outputs; independently derive requirements before consulting them. Failed/exposed historical code2/final2 gates do not supply independent assessment; fresh replacements and current check provenance must be evaluated. Current restored seed is not the historical fixed runtime input. Fixed bytes/preimages remain in immutable public archives.','original_preparation_raw_manifest':record(O/'preparation-raw-fingerprints.json'),'review_excluded':['E/S6-actual-criteria.json states/assessments','Root inspection/classification conclusions, S6-root-* diagnostics and queued corrections','Author current/prior S6 builder narratives and old OUTER preparation/S6/whole verdicts','Root intake drafts and author terminal closeout report','Mixed first code author checks and final2 prior finding exposure as correctness input; retain neutral historical deviation/lifecycle only'],'current_state':'Private preview stopped/abandoned, original128/full4353 restored. No publication authority. Six central/article authority bytes are now explicitly changed and separately reviewed; all earlier165/168 preservation claims are qualified at their original observation times.'})
print(json.dumps({'criteria':len(criterion_rows),'ledger':len(definitions['ledger_mapping']),'neutral_deviations':len(neutral),'domain_raw':len(domain),'authority':len(authority)}))
