from pathlib import Path
from datetime import datetime,timezone
from collections import Counter
import hashlib,json,os,subprocess,sys
C=Path('/Users/rccurtrightjr./projects/fs-dev/ai/RC-MacAir-15/mission-control');J=C/'jobs/commit-supervisor/rehearsal-20261004-s6';P=Path('/private/tmp/mc-s6-commit-supervisor-20261004/candidate');R=C.parents[2];K=C/'.agents/skills/mc-commit-supervisor'
def fp(p):
 p=Path(p)
 if not p.exists() and not p.is_symlink():return {'exists':False}
 s=p.lstat();b=os.fsencode(os.readlink(p)) if p.is_symlink() else p.read_bytes();return {'exists':True,'kind':'symlink' if p.is_symlink() else 'file','mode':oct(s.st_mode),'sha256':hashlib.sha256(b).hexdigest()}
def git(repo,*args):return subprocess.check_output(['git','-C',str(repo),*args],env=dict(os.environ,GIT_OPTIONAL_LOCKS='0'))
pin=json.loads((J/'evidence/fix-xy-final3-identity.json').read_text());py=json.loads((J/'evidence/fix-xy-python-pre2.json').read_text());node=json.loads((J/'evidence/fix-xy-node17-current-bindings.json').read_text());owned={n:fp(P/n) for n in pin['owned']};authority={n:fp(n) for n in pin['authority']};config={n:fp(n) for n in pin['configuration']};py_mis=[n for n,v in py['dependencies'].items() if fp(n)!=v];node_mis=[n for n,v in node['unique_source_dependencies'].items() if fp(n)!=v];owned_deltas=[n for n in owned if owned[n]!=pin['owned'][n]];assert not py_mis and not node_mis;assert authority==pin['authority'] and config==pin['configuration'];status=git(P,'status','--porcelain=v1','-z','--untracked-files=all').hex();index=git(P,'ls-files','--stage','-z').hex();assert index==pin['index_z_hex'];watch='rehearsal-workspace/ai/MC-S6/watcher-proof-runtime-2.md'
if sys.argv[1]=='pre':assert not owned_deltas and status==pin['status_z_hex']
else:
 assert owned_deltas==[watch],owned_deltas
 assert (P/watch).read_text()=='# Watcher sample\n\nA private fixture document was created.\n'
 before=Counter(bytes.fromhex(pin['status_z_hex']).split(b'\0'));after=Counter(bytes.fromhex(status).split(b'\0'));assert after-before==Counter({('?? '+watch).encode():1}) and not before-after
ktree={str(p):fp(p) for p in sorted((K/'tests').rglob('*')) if p.is_file() or p.is_symlink()}
d={'at':datetime.now(timezone.utc).isoformat(),'actor':'/root/s6_supervisor_fix_xy_1','kind':'CURRENT_RUNTIME_SOURCE_CHECK_DEPENDENCY_BRIDGE','mode':sys.argv[1],'review_pin':str(J/'evidence/fix-xy-final3-identity.json'),'review_pin_sha256':hashlib.sha256((J/'evidence/fix-xy-final3-identity.json').read_bytes()).hexdigest(),'owned':owned,'expected_runtime_only_deltas':owned_deltas,'authority':authority,'configuration':config,'index_z_hex':index,'status_z_hex':status,'candidate_physical_index':fp(P/'.git/index'),'candidate_head':git(P,'rev-parse','HEAD').decode().strip(),'candidate_refs':git(P,'show-ref').decode(),'candidate_config':fp(P/'.git/config'),'source_head':git(R,'rev-parse','HEAD').decode().strip(),'source_refs':git(R,'show-ref').decode(),'source_physical_index':fp(R/'.git/index'),'source_config':fp(R/'.git/config'),'current55_unique_dependencies':len(py['dependencies']),'current55_mismatches':py_mis,'current17_unique_dependencies':len(node['unique_source_dependencies']),'current17_mismatches':node_mis,'whole_installed_tests_tree':ktree,'runtime_helper':fp(Path(__file__)), 'identity_helper':fp(J/'fix_xy_runtime_identity.mjs'),'limits':'Read-only current source/check metadata. Runtime2 watcher is declared owned evidence and excluded from hypothetical correction commit. Product/code/Wiki/startup drift would fail. Profile runtime/db/cache effects are separate.'}
if sys.argv[1]!='pre':
 b=json.loads(Path(sys.argv[3]).read_text());keys=['candidate_physical_index','candidate_head','candidate_refs','candidate_config','source_head','source_refs','source_physical_index','source_config','whole_installed_tests_tree','runtime_helper','identity_helper'];assert all(d[k]==b[k] for k in keys);d['pre_path']=sys.argv[3];d['pre_sha256']=hashlib.sha256(Path(sys.argv[3]).read_bytes()).hexdigest();d['protected_fields_equal']=keys
p=Path(sys.argv[2]);p.open('x').write(json.dumps(d,indent=2)+'\n');p.chmod(0o444);print(json.dumps({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'owned':len(owned),'authority':len(authority),'55deps':len(py['dependencies']),'17deps':len(node['unique_source_dependencies']),'whole_tests':len(ktree),'expected_runtime_only_deltas':owned_deltas}))
