from pathlib import Path
import json, hashlib, subprocess
CAP=Path(__file__).resolve().parent
ROOT=CAP.parents[3]
WV='ai/RC-MacAir-15/Wiki/001-Workspaces_And_Views/'
changes={}
def change(rel,old,new):
 p=WV+rel+'/PAGE.md'; before=changes.get(p,(ROOT/p).read_text()); assert before.count(old)==1,(p,old);changes[p]=before.replace(old,new)
change('000-Workspaces_And_Views','## Reading routes\n','## Reading routes\n\n[Platform And Plugins](../../011-Platform_And_Plugins/000-Platform_And_Plugins/PAGE.md) explains the approved shell, component and plugin boundaries, copied editable instances, and canonical file surfaces. This section retains workspace binding, local agent context and the WV gap register.\n')
change('000-Workspaces_And_Views/001-Vision','Each installed view has editable local resources: its agent persona, skills,','Each installed view receives a separate editable copy of the plugin template, including its agent persona, AGENTS.md, skills,')
change('000-Workspaces_And_Views/001-Vision','This design leaves a useful boundary', 'The approved presentation model combines a useful standard component library with registered plugin contributions. Instances can configure and compose these pieces; specialized executable components stay in protected plugins. The platform shell owns tab, drawer and popup/window hosts, while the canonical file surface owns file presentation/editing and platform services own save/history. Components render on the client with explicit data/actions; they do not gain ambient service or database access. [Platform And Plugins](../../../011-Platform_And_Plugins/000-Platform_And_Plugins/PAGE.md) explains these layers.\n\nThe intended agent starts in its own view-instance folder with project-root orientation and authorized project-wide working access, subject to protected System/plugin boundaries. Its own AGENTS and persona enter harness context; its skills are available through the harness, with bodies read when needed. Other views\' instructions and skills are deliberately read when requested, not automatically injected. Such a read does not change identity, working directory or capabilities. [View Configuration And Agents](../../022-View_Configuration_And_Agents/PAGE.md) separates this settled direction from the remaining harness mechanics and current startup behavior.\n\nThis design leaves a useful boundary')
change('000-Workspaces_And_Views/002-Decisions','- **Instances carry local agent resources.** An instance can contain a persona, skills, special sub-agent definitions, workflows, ordinary configuration, theme, and state. It points to its plugin for display and content behavior. Whether and how a harness loads those resources still needs a separate context contract.', '- **Instances carry copied local agent resources.** The protected plugin supplies a template; the server copies it into a separate editable instance and binds that instance to the installed dependency. The copy can contain persona, AGENTS.md, skills, special sub-agent definitions, workflows, ordinary configuration, theme, and state. Copied instructions and configuration do not become privileged executable code.\n- **Agent orientation is view-local within the project.** The agent starts with its own view-instance working directory and project-root orientation/access, within authorized project scope and protected System/plugin boundaries. Own AGENTS/persona enter harness context; own skills are exposed through the harness with bodies read as needed. Other-view instructions/skills are manually read when requested, not eagerly injected; reads do not automatically change identity, working directory or capabilities. WV-O06 now concerns harness-specific mechanics, not this intended behavior.\n- **Plugin presentation uses platform hosts.** A useful standard library can be configured and composed, and protected plugins can contribute registered presentation components with explicit data/actions. The shell owns tabs, drawers and popup/window lifecycle. Collections can open the canonical file surface in the current tab with a return route or another tab, retaining selection/filter/navigation state; file editing and platform save/history keep their owners. See [Platform Boundaries](../../../011-Platform_And_Plugins/001-Platform_Boundaries/PAGE.md) and [Tabs, Drawers And Files](../../../011-Platform_And_Plugins/004-Tabs_Drawers_And_Files/PAGE.md).')
change('000-Workspaces_And_Views/002-Decisions','6. **Agent context:** define how per-view personas, skills, agents, and workflows are discovered and loaded before claiming that a harness uses them.', '6. **Agent context mechanics (WV-O06):** define harness-specific working-directory setup, discovery and assembly of local context, skill collision handling and enforcement before claiming end-to-end support. The view-local orientation, own AGENTS/persona context, skills available on demand and deliberate manual other-view reads are settled above; this gate does not require a new skill override/precedence model. See [View Configuration And Agents](../../022-View_Configuration_And_Agents/PAGE.md#approved-agent-orientation).')
change('000-Workspaces_And_Views/003-Unfinished_Work','**Target:** Editable view instances can supply persona, skills, special sub-agent definitions and workflows to the AI working in that view. **Current limit:** the inspected OpenCode launch starts from the project root; the inspected view-registry route does not establish assembly of those instance-local resources. This is an unverified end-to-end context path, not proof that no other context mechanism exists. **Remaining capability:** define discovery, precedence, assembly and trust at actual harness activation. **Owner:** harness and context assembly. **Decision gate:** WV-O06 before claiming resources are loaded.', '**Target:** The agent starts in its own editable view-instance folder with project-root orientation and authorized project-wide working access, subject to protected System/plugin boundaries. Own AGENTS/persona enter harness context; own skills are available through the harness with bodies loaded as needed. Other-view instructions/skills are deliberately read when requested, without automatic identity, capability or working-directory changes. **Current limit:** the inspected OpenCode launch still uses the supplied project root for both `--dir` and process working directory; the inspected view-registry route does not establish assembly of instance-local resources. This is an unverified end-to-end context path, not proof that no other context mechanism exists. **Remaining capability:** implement the settled orientation through harness-specific working-directory setup, discovery, assembly, skill collision handling and enforcement at activation. **Owner:** harness and context assembly. **Decision gate:** WV-O06 for those mechanics before claiming end-to-end support; intended local context and manual cross-view reads are settled.')
change('000-Workspaces_And_Views/003-Unfinished_Work','## Coverage boundary\n','## Coverage boundary\n\n[Platform And Plugins unfinished work](../../../011-Platform_And_Plugins/000-Platform_And_Plugins/002-Unfinished_Work/PAGE.md) owns component hosting, shell/file reuse, hybrid iframe operations and external-store mediation gaps. Provisioning, instance identity, local context and placement remain under the WV IDs here.\n')
change('002-View_Architecture','## Content is a separate binding\n', '## Approved presentation boundary\n\nA protected view plugin supplies content behavior and may contribute reusable presentation through the platform host contract. Its template is copied into a separate editable instance; configuring or composing registered components there does not create executable authority. Components render on the client from explicit data/actions. The platform shell retains tab, drawer and popup/window identity, focus and lifecycle; the canonical file-type registry and file surface retain presentation/editing, with save/history owned by platform services. A collection may open that file surface in its current tab with a return route or another tab while retaining selection/filter/navigation state. This is approved direction, not a claim that fixed current dispatch implements a general plugin loader or a second tab/save store. See [Composable Presentation](../../011-Platform_And_Plugins/003-Composable_Presentation/PAGE.md) and [Tabs, Drawers And Files](../../011-Platform_And_Plugins/004-Tabs_Drawers_And_Files/PAGE.md).\n\n## Content is a separate binding\n')
change('006-Custom_Iframe','Use [Browser]', 'The approved hybrid direction places standard host pieces beside a custom iframe region and offers narrow authorized platform-operation requests. It does not grant unrestricted server, Node or database access; the current embedding paths do not establish that bridge. An iframe-side UI library is optional and deferred. [Custom Iframe Composition](../../011-Platform_And_Plugins/006-Custom_Iframe_Composition/PAGE.md) owns the target and open interface choices.\n\nUse [Browser]')
change('021-Workspace_Compositions','Each instance then refers back to its protected plugin. Persona, skills,', 'Each instance then refers back to its protected plugin. Installing that dependency and creating an editable instance are separate operations; the copied template does not become privileged implementation code. [Plugin Templates And Instances](../../011-Platform_And_Plugins/002-Plugin_Templates_And_Instances/PAGE.md) explains the package/copy boundary. Persona, AGENTS.md, skills,')
change('022-View_Configuration_And_Agents','an agent persona, skills, special sub-agent definitions and workflows.', 'an agent persona, AGENTS.md, skills, special sub-agent definitions and workflows supplied by a copied plugin template.')
change('022-View_Configuration_And_Agents','## Current implementation and gap\n','## Approved agent orientation\n\nThe agent starts with its own view-instance folder as working directory, while knowing the project root and retaining authorized project-wide working access. System and protected plugin boundaries still apply; project scope does not authorize direct protected mutations. The server provisions the separate editable template copy and binding. An instruction file or copied template does not confer executable powers. [Plugin Templates And Instances](../../011-Platform_And_Plugins/002-Plugin_Templates_And_Instances/PAGE.md) owns that distinction.\n\nThe instance\'s own AGENTS and persona enter harness context. Its skills are exposed through the harness as an available catalog, with their bodies read on demand rather than necessarily pasted into initial context. Other views\' instructions and skills are deliberately read when requested, not automatically injected into every view\'s context. Manual reads do not automatically rebind identity, change working directory or grant capabilities. Harness-specific discovery, context assembly, skill collision handling and enforcement remain WV-O06 mechanics; the intended orientation is settled.\n\n## Current implementation and gap\n')
change('022-View_Configuration_And_Agents','**WV-G04 — view-local agent context:** current OpenCode startup uses the project root as its working directory; no current view-instance persona/skills/sub-agent/workflow assembly is established by these paths. Adding files to a future instance folder alone would not prove that a chat launched in that view receives them. Harness/context integration must define discovery, precedence, assembly and trust before claiming view-local agent behavior (WV-O06). This page specifies where those resources should live, not that they are loaded today.', '**WV-G04 — view-local agent context:** in the inspected activation route, `thread-ws-handlers.js` passes the workspace manager\'s project root through `harness/compat.js` to OpenCode. The adapter uses that supplied `projectRoot` for `--dir` and the spawned process working directory; it does not switch that launch to a view-instance folder. These source paths and the view registry do not establish the intended local persona/AGENTS/skills/sub-agent/workflow assembly end to end. Adding files alone would not prove that a chat launched in that view receives them, and this bounded inspection is not proof that no other context mechanism exists. Harness/context integration must implement the settled orientation and resolve working-directory setup, discovery, assembly, skill collision handling and enforcement (WV-O06). No runtime verification is claimed.')
change('022-View_Configuration_And_Agents','    - fusion-studio-server/lib/harness/opencode/index.js\n','    - fusion-studio-server/lib/harness/opencode/index.js\n    - fusion-studio-server/lib/harness/compat.js\n    - fusion-studio-server/lib/ws/thread-ws-handlers.js\n')
change('007-File_View','The approved future plugin supplies the Files behavior while its editable instance selects content and agent configuration within declared capabilities.', 'The approved future plugin supplies the Files behavior while its editable instance selects content and agent configuration within declared capabilities. The Files view is distinct from the reusable canonical file surface: a collection may open that surface in its current tab with a return route or another tab, retaining collection state while canonical file editing and platform save/history keep their owners. [Tabs, Drawers And Files](../../011-Platform_And_Plugins/004-Tabs_Drawers_And_Files/PAGE.md) explains this target without adding another editor or save implementation.')
manifest=[]
for i,(path,text) in enumerate(changes.items(),1):
 before=(ROOT/path).read_bytes();sha=hashlib.sha256(before).hexdigest();proposal=CAP/f'S04-{i:02d}-proposal.md';proposal.write_text(text)
 manifest.append({'path':path,'proposal':str(proposal.relative_to(ROOT)),'before_sha256':sha})
(CAP/'S04-PROPOSALS.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(manifest,indent=2))
