import json,hashlib,os,datetime,copy
from pathlib import Path
E=Path(__file__).resolve().parent;C=E.parents[2];R=C.parents[2];at=datetime.datetime.now(datetime.timezone.utc).isoformat()
def load(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
report=E/'S6-acceptance-review-1.md';assert sha(report)=='6434b6a9192b87b4ee084394fa0de3077d12f07a1a4710bedcf57c47af67ea38'
assert sha(R/'.git/index')=='f37b5bfc9a44893b132661290fe095ddafccb79bed38ca9007dc3803d2ff7966'
facts=[('S6-ACCEPTANCE-P01','Initial pure rev-parse root lookup omitted explicit optional-lock flag; subsequent Git reads cleared inherited Git variables and set GIT_OPTIONAL_LOCKS=0.','No reconstruction of initial invocation; native disclosure and exact retained source index establish no observed index effect.'),('S6-ACCEPTANCE-P02','Oversized inspection outputs and guessed locator/schema probes were corrected through bounded source reads and complete parsed comparisons.','Initial errors/truncation do not prove coverage; corrected exact inspections and complete raw fingerprints provide subsequent evidence.'),('S6-ACCEPTANCE-P03','Initial symlink comparator followed target contents; corrected comparator hashes the exact link-target bytes.','Initial comparator was not accepted as proof; corrected lstat/readlink semantics agree with original immutable payloads.')]
entries=[]
for id,change,risk in facts:
 entries.append({'id':id,'original_requirement':'Fresh read-only original-authority review with complete current/source evidence, explicit optional-lock Git reads and honest limits','actual_change':change,'reason_authority':'Report-only procedural disclosure at actual fresh independent native terminal; no product implementation change','files':[],'checks':'Current original4353/owned128/blob/status semantics, six immutable archives, all3403 current manifest fingerprints and current source physical index independently checked; full corrected read coverage retained','observable_effect':'Read-only diagnostic correction; no source/candidate/index/profile/runtime write; no required outcome waived','risk':risk,'downstream_impact':'Preserve factual procedural limits at whole SPEC/owner handoff; no product repair or repeated lower gate necessary','classification':'accepted','classification_owner':'/root','root_basis':risk,'at':at})
source=E/'S6-acceptance-procedural-deviations.json';save(source,{'at':at,'scope':'Three terminal full S6 review procedural facts only','entries':entries,'raw_evidence':{'path':str(report),'sha256':sha(report)},'no_reviewed_byte_change':True})
neutral=load(E/'SPEC-neutral-deviations.json');assert len(neutral['entries'])==104
for e in entries:
 n={k:copy.deepcopy(e[k])for k in ['id','original_requirement','actual_change','reason_authority','files','checks','observable_effect','risk','downstream_impact']};n.update(scope='S6 acceptance procedural facts',original_source=str(source),provenance_rule='Neutral factual eight fields only; original source/raw OUTER report/classification fields excluded from fresh reviewer inputs.');neutral['entries'].append(n)
digest=sha(source);target=E/'SPEC-neutral-source-preimages'/(hashlib.sha256(str(source).encode()).hexdigest()[:16]+'-'+source.name)
with target.open('xb')as f:f.write(source.read_bytes())
target.chmod(0o444);neutral['source_hashes'][str(source)]=digest;neutral['source_snapshots'][str(source)]={'path':str(target),'sha256':digest,'mode':oct(target.stat().st_mode),'scope':'Complete provenance only; excluded prior OUTER report pointers/classifications are not fresh reviewer inputs.'};neutral.update(at=at,contextual_entry_count=107,unique_ids=101);save(E/'SPEC-neutral-deviations.json',neutral)
life=load(E/'S6-full-acceptance-lifecycle.json');life.update(state='completed',result='CLEAN',terminal_observed_at=at,native_terminal='Actual FINAL_ANSWER and exact-prefix list_agents completed; no children',raw_report=str(report),raw_sha256=sha(report),raw_bytes=report.stat().st_size,first_clean_stop=True);save(E/'S6-full-acceptance-lifecycle.json',life)
manifest=load(E/'S6-closeout-manifest.json');revisions=[]
for row in manifest['authority']+manifest['changed_documentation']:
 p=Path(row['path']);revisions.append({'path':str(p),'sha256':sha(p),'mode':p.stat().st_mode,'scope':'Current source/authority/documentation dependency of full S6'})
receipt={'at':at,'actor':'/root','result':'S6_ACCEPTED','builder':'/root/s6_builder','builder_terminal':'S6-root-builder-terminal.json','fresh_own_reviewer':'/root/s6_builder/s6_full_review_1','fresh_root_reviewer':'/root/s6_acceptance_1','root_review':{'path':str(report),'sha256':sha(report),'native_terminal':True,'result':'CLEAN'},'current_manifest_sha256':sha(E/'S6-closeout-manifest.json'),'original_criteria':15,'refined_criteria':19,'S6_deviation_contexts':91,'all_classified':True,'material_findings':[],'advisory':'Restart Wiki unwrapped paragraph preference; current hard wrapping has no factual/observable acceptance impact; optional future prose normalization','inspection':['S6-root-current-frozen-inputs.json','S6-root-current-python-dependency-readback.json','S6-root-closeout-readback.json','S6-root-recovery-inspection.json','S6-root-builder-terminal.json'],'remaining':'Full current suite, final preservation/static checks and fresh whole SPEC integration gate; owner setup acceptance afterward','current_ready':False,'protected_live_DB_bytes':'volatile; identity preserved; no copy/restore','historical_closure':'Unavailable API; actual native terminals observed'}
save(E/'S6-full-acceptance.json',receipt)
ledger=load(E/'slice-ledger.json');s=ledger['slices'][-1];assert s['id']=='S6';s.update(state='accepted',phase='Full S6 accepted; final SPEC integration pending',accepted_at=at,current_revision=revisions,acceptance_receipt=str(E/'S6-full-acceptance.json'),preparation_only=False,full_deviation_context_count=91,full_deviation_classification_sources=['S6-preparation-deviation-classifications.json','S6-runtime-deviations.json','S6-first-candidate-deviation-classifications.json','S6-revised-leaf-deviation-classifications.json','S6-revised-supervisor-deviation-classifications.json','S6-refusal-deviation-classifications.json','S6-first-interruption-deviation-classifications.json','S6-recovery-deviation-classifications.json','S6-closeout-deviation-classifications.json','S6-reviewer-procedural-classifications.json','S6-acceptance-procedural-deviations.json']);s['reviewers'].append({'identity':'/root/s6_acceptance_1','gate':'orchestrator_full_S6_acceptance','result':'CLEAN','terminal':True,'fork_turns':'none','close_agent':'unavailable','report':str(report),'sha256':sha(report)});save(E/'slice-ledger.json',ledger)
criteria=load(E/'S6-actual-criteria.json')
for r in criteria['criteria']:
 if r['id']=='S6-A18':r.update(state='accepted_current_full_S6',evidence=[str(E/'S6-full-acceptance.json'),str(E/'S6-closeout-manifest.json')])
 if r['id']=='S6-A19':r.update(state='fresh root full S6 CLEAN; fresh whole SPEC gate pending',evidence=[str(report),str(E/'S6-full-acceptance.json')])
criteria['last_root_progress_at']=at;save(E/'S6-actual-criteria.json',criteria)
active={'at':at,'actor':'/root','accepted_slices':['S1','S2','S3','S4','S5','S6'],'actual_recovery_complete':True,'private_preview_stopped':True,'S6_acceptance':{'path':str(E/'S6-full-acceptance.json'),'sha256':sha(E/'S6-full-acceptance.json')},'no_current_runtime_readiness_claim':True,'scope':'Final current regression/static/read-only preservation gates; real successful live fixed rehearsals retained on exact historical bytes'}
with(E/'SPEC-final-check-activation.json').open('x')as f:json.dump(active,f,indent=2);f.write('\n')
for name in ['SPEC-final-packet.py','SPEC-final-report-draft.md']:
 p=E/name;text=p.read_text();text=text.replace('==104','==107').replace('==98','==101').replace('104 contextual','107 contextual').replace('98 distinct','101 distinct').replace("'contextual_entry_count':104","'contextual_entry_count':107").replace("'unique_ids':98","'unique_ids':101").replace("'deviation_contexts':104","'deviation_contexts':107").replace('104 factual contexts/98 distinct IDs','107 factual contexts/101 distinct IDs');p.write_text(text)
continuation=load(E/'orchestrator-runtime-continuation.json');continuation.update(at=at,accepted_slices=active['accepted_slices'],active_direct_child=None,active_phase='Final current suites/checks activated',next_root_action='Run current suite55/17 and static/preservation once; inspect raw results; fresh whole SPEC review');save(E/'orchestrator-runtime-continuation.json',continuation)
print(json.dumps({'result':'ALL_SIX_ACCEPTED','neutral_contexts':107,'unique_ids':101,'activation':str(E/'SPEC-final-check-activation.json')}))
